package dev.rafex.insightbloom.users.adapters.outbound.sqlite;

import dev.rafex.insightbloom.users.domain.model.Conference;
import dev.rafex.insightbloom.users.domain.model.CanvasConfig;
import dev.rafex.insightbloom.users.domain.model.OnDemandCuePoint;
import dev.rafex.insightbloom.users.domain.model.ConferenceStatus;
import dev.rafex.insightbloom.users.domain.ports.ConferenceRepository;

import java.sql.*;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class SqliteConferenceRepository implements ConferenceRepository {
    private final DatabaseManager db;

    public SqliteConferenceRepository(DatabaseManager db) {
        this.db = db;
    }

    @Override
    public void save(Conference conference) {
        // NOTA (2026-07-17): sandbox_variant/sandbox_pool_size/sandbox_internet_enabled/
        // sandbox_extra_packages/sandbox_remote_git_url/sandbox_jvm_heap_mb agregados a esta
        // lista -- antes de este fix el INSERT OR REPLACE no los incluia, asi que cada save()
        // los pisaba con NULL/default en la fila real (aunque el objeto en memoria los tuviera
        // seteados), y map() tampoco los leia de vuelta -- la config de sandbox del Dashboard
        // nunca sobrevivia a un reload desde la DB. Confirmado en vivo: el pod
        // sandbox-e998a2bf-0 tenia label sandbox-variant=python, que es el DEFAULT_VARIANT del
        // codigo (AssignSandboxUseCase), no algo que un organizador hubiera configurado.
        String sql = """
            INSERT OR REPLACE INTO conferences
              (uuid, friendly_id, name, created_by_user_uuid, status, created_at, updated_at, expires_at, latitude, longitude, event_date, venue, start_time, end_time, name_auto_generated, presentation_source_url, flyer_base64, description, visibility, schedule_markdown, schedule_layout, public_theme, timezone_id, reminder_sent_at, day_before_reminder_sent_at, seating_mode, capacity, reserved_count, venue_map_base64, event_type_key, notes_purged_at, diagram_xml, diagram_published_svg, diagram_updated_at, diagram_version, diagram_purged_at, whiteboard_scene_json, whiteboard_published_svg, whiteboard_updated_at, whiteboard_version, sandbox_variant, sandbox_pool_size, sandbox_internet_enabled, sandbox_remote_git_url, sandbox_jvm_heap_mb, sandbox_seats_per_pod, sandbox_cli_pool_size, sandbox_cli_lazyvim_pool_size, max_devices_per_user, max_accounts_per_device, canvas_tool, canvas_audience_mode, ticket_price, ticket_currency, certificate_engine, ticket_sales_enabled, on_demand_video_provider, on_demand_video_url)
            VALUES (
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
                , ?, ?, ?, ?
            )
        """;
        try (Connection conn = db.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, conference.getUuid());
            ps.setString(2, conference.getFriendlyId());
            // Bases antiguas podían contener conferencias sin nombre aunque el esquema actual
            // lo declara NOT NULL. Nunca permitimos que una actualización incidental (por
            // ejemplo, durante la limpieza de un sandbox) vuelva a intentar escribir ese valor.
            final String name = conference.getName();
            ps.setString(3, name != null && !name.isBlank() ? name : conference.getFriendlyId());
            ps.setString(4, conference.getCreatedByUserUuid());
            ps.setString(5, conference.getStatus().name());
            ps.setString(6, conference.getCreatedAt().toString());
            ps.setString(7, conference.getUpdatedAt().toString());
            ps.setString(8, conference.getExpiresAt() != null ? conference.getExpiresAt().toString() : null);
            if (conference.getLatitude() != null) ps.setDouble(9, conference.getLatitude());
            else ps.setNull(9, Types.REAL);
            if (conference.getLongitude() != null) ps.setDouble(10, conference.getLongitude());
            else ps.setNull(10, Types.REAL);
            ps.setString(11, conference.getEventDate());
            ps.setString(12, conference.getVenue());
            ps.setString(13, conference.getStartTime());
            ps.setString(14, conference.getEndTime());
            ps.setInt(15, conference.isNameAutoGenerated() ? 1 : 0);
            ps.setString(16, conference.getPresentationSourceUrl());
            ps.setString(17, conference.getFlyerBase64());
            ps.setString(18, conference.getDescription());
            ps.setString(19, conference.getVisibility());
            ps.setString(20, conference.getScheduleMarkdown());
            ps.setString(21, conference.getScheduleLayout());
            ps.setString(22, conference.getPublicTheme());
            if (conference.getTimezoneId() != null) ps.setInt(23, conference.getTimezoneId());
            else ps.setNull(23, Types.INTEGER);
            ps.setString(24, conference.getReminderSentAt() != null ? conference.getReminderSentAt().toString() : null);
            ps.setString(25, conference.getDayBeforeReminderSentAt() != null ? conference.getDayBeforeReminderSentAt().toString() : null);
            ps.setString(26, conference.getSeatingMode());
            if (conference.getCapacity() != null) ps.setInt(28, conference.getCapacity());
            else ps.setNull(28, Types.INTEGER);
            ps.setInt(29, conference.getReservedCount());
            ps.setString(30, conference.getVenueMapBase64());
            ps.setString(31, conference.getEventTypeKey());
            ps.setString(32, conference.getNotesPurgedAt() != null ? conference.getNotesPurgedAt().toString() : null);
            ps.setString(33, conference.getDiagramXml());
            ps.setString(34, conference.getDiagramPublishedSvg());
            ps.setString(35, conference.getDiagramUpdatedAt() != null ? conference.getDiagramUpdatedAt().toString() : null);
            ps.setLong(36, conference.getDiagramVersion());
            ps.setString(37, conference.getDiagramPurgedAt() != null ? conference.getDiagramPurgedAt().toString() : null);
            ps.setString(38, conference.getWhiteboardSceneJson());
            ps.setString(39, conference.getWhiteboardPublishedSvg());
            ps.setString(40, conference.getWhiteboardUpdatedAt() != null ? conference.getWhiteboardUpdatedAt().toString() : null);
            ps.setLong(41, conference.getWhiteboardVersion());
            ps.setString(42, conference.getSandboxVariant());
            if (conference.getSandboxPoolSize() != null) ps.setInt(43, conference.getSandboxPoolSize());
            else ps.setNull(43, Types.INTEGER);
            final Integer internetEnabled = conference.getSandboxInternetEnabled();
            ps.setInt(44, internetEnabled != null ? internetEnabled : 0);
            ps.setString(45, conference.getSandboxRemoteGitUrl());
            if (conference.getSandboxJvmHeapMb() != null) ps.setInt(46, conference.getSandboxJvmHeapMb());
            else ps.setNull(46, Types.INTEGER);
            if (conference.getSandboxSeatsPerPod() != null) ps.setInt(47, conference.getSandboxSeatsPerPod());
            else ps.setNull(47, Types.INTEGER);
            if (conference.getSandboxCliPoolSize() != null) ps.setInt(48, conference.getSandboxCliPoolSize());
            else ps.setNull(48, Types.INTEGER);
            if (conference.getSandboxCliLazyVimPoolSize() != null) ps.setInt(49, conference.getSandboxCliLazyVimPoolSize());
            else ps.setNull(49, Types.INTEGER);
            if (conference.getMaxDevicesPerUser() != null) ps.setInt(50, conference.getMaxDevicesPerUser());
            else ps.setNull(50, Types.INTEGER);
            if (conference.getMaxAccountsPerDevice() != null) ps.setInt(51, conference.getMaxAccountsPerDevice());
            else ps.setNull(51, Types.INTEGER);
            ps.setString(52, conference.getCanvasTool());
            ps.setString(53, conference.getCanvasAudienceMode());
            ps.setString(54, conference.getTicketPrice());
            ps.setString(55, conference.getTicketCurrency());
            ps.setString(56, conference.getCertificateEngine());
            ps.setInt(57, conference.isTicketSalesEnabled() ? 1 : 0);
            ps.setString(58, conference.getOnDemandVideoProvider());
            ps.setString(59, conference.getOnDemandVideoUrl());
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public void replaceCanvasConfigs(final String conferenceUuid, final List<CanvasConfig> configs) {
        final String deleteSql = "DELETE FROM conference_canvas_configs WHERE conference_uuid = ?";
        final String insertSql = "INSERT INTO conference_canvas_configs "
                + "(conference_uuid, canvas_tool, audience_mode) VALUES (?, ?, ?)";
        try (Connection conn = db.getConnection()) {
            conn.setAutoCommit(false);
            try (PreparedStatement delete = conn.prepareStatement(deleteSql);
                 PreparedStatement insert = conn.prepareStatement(insertSql)) {
                delete.setString(1, conferenceUuid);
                delete.executeUpdate();
                for (final CanvasConfig config : configs) {
                    insert.setString(1, conferenceUuid);
                    insert.setString(2, config.tool());
                    insert.setString(3, config.audienceMode());
                    insert.addBatch();
                }
                insert.executeBatch();
                conn.commit();
            } catch (SQLException e) {
                conn.rollback();
                throw e;
            } finally {
                conn.setAutoCommit(true);
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public void replaceOnDemandCuePoints(final String conferenceUuid, final List<OnDemandCuePoint> cuePoints) {
        final String deleteSql = "DELETE FROM conference_on_demand_cue_points WHERE conference_uuid = ?";
        final String insertSql = "INSERT INTO conference_on_demand_cue_points "
                + "(conference_uuid, at_seconds, label, tool_path, sort_order) VALUES (?, ?, ?, ?, ?)";
        try (Connection conn = db.getConnection()) {
            conn.setAutoCommit(false);
            try (PreparedStatement delete = conn.prepareStatement(deleteSql);
                 PreparedStatement insert = conn.prepareStatement(insertSql)) {
                delete.setString(1, conferenceUuid);
                delete.executeUpdate();
                int sortOrder = 0;
                for (final OnDemandCuePoint cuePoint : cuePoints) {
                    insert.setString(1, conferenceUuid);
                    insert.setInt(2, cuePoint.atSeconds());
                    insert.setString(3, cuePoint.label());
                    insert.setString(4, cuePoint.toolPath());
                    insert.setInt(5, sortOrder++);
                    insert.addBatch();
                }
                insert.executeBatch();
                conn.commit();
            } catch (SQLException e) {
                conn.rollback();
                throw e;
            } finally {
                conn.setAutoCommit(true);
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public void delete(String uuid) {
        String sql = "DELETE FROM conferences WHERE uuid = ?";
        try (Connection conn = db.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, uuid);
            ps.executeUpdate();
            try (PreparedStatement canvas = conn.prepareStatement(
                    "DELETE FROM conference_canvas_configs WHERE conference_uuid = ?")) {
                canvas.setString(1, uuid);
                canvas.executeUpdate();
            }
            try (PreparedStatement cuePoints = conn.prepareStatement(
                    "DELETE FROM conference_on_demand_cue_points WHERE conference_uuid = ?")) {
                cuePoints.setString(1, uuid);
                cuePoints.executeUpdate();
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public Optional<Conference> findByUuid(String uuid) {
        return query("SELECT * FROM conferences WHERE uuid = ?", uuid);
    }

    @Override
    public Optional<Conference> findByFriendlyId(String friendlyId) {
        return query("SELECT * FROM conferences WHERE friendly_id = ?", friendlyId);
    }

    @Override
    public Optional<Conference> findByShortCode(String shortCode) {
        // Últimos 7 hex chars del UUID (sin guiones): e.g. "b338a5a" de "...b95e3b338a5a"
        return query(
            "SELECT * FROM conferences WHERE LOWER(SUBSTR(REPLACE(uuid,'-',''), -7)) = LOWER(?)",
            shortCode
        );
    }

    @Override
    public boolean existsByFriendlyId(String friendlyId) {
        String sql = "SELECT 1 FROM conferences WHERE friendly_id = ?";
        try (Connection conn = db.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, friendlyId);
            return ps.executeQuery().next();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public List<Conference> findAll() {
        final List<Conference> list = new ArrayList<>();
        try (Connection conn = db.getConnection(); PreparedStatement ps = conn.prepareStatement(
                "SELECT * FROM conferences ORDER BY created_at DESC");
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) list.add(map(conn, rs));
        } catch (SQLException e) { throw new RuntimeException(e); }
        return list;
    }

    @Override
    public List<Conference> findByUser(String userUuid) {
        List<Conference> list = new ArrayList<>();
        // El panel debe incluir tanto eventos propios como eventos donde el usuario tiene
        // una asignación operativa (moderador, host, presentador, etc.).
        String sql = """
            SELECT DISTINCT c.*
            FROM conferences c
            LEFT JOIN event_roles er ON er.event_uuid = c.uuid AND er.user_uuid = ?
            WHERE c.created_by_user_uuid = ? OR er.user_uuid IS NOT NULL
            ORDER BY c.created_at DESC
        """;
        try (Connection conn = db.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, userUuid);
            ps.setString(2, userUuid);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) list.add(map(conn, rs));
        } catch (SQLException e) { throw new RuntimeException(e); }
        return list;
    }

    @Override
    public List<Conference> findPendingReminder() {
        final List<Conference> list = new ArrayList<>();
        final String sql = """
            SELECT * FROM conferences
            WHERE status = 'ACTIVE' AND event_date IS NOT NULL AND start_time IS NOT NULL
              AND reminder_sent_at IS NULL
        """;
        try (Connection conn = db.getConnection(); PreparedStatement ps = conn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery()) {
            while (rs.next()) list.add(map(conn, rs));
        } catch (SQLException e) { throw new RuntimeException(e); }
        return list;
    }

    public List<Conference> findPendingDayBeforeReminder() {
        final List<Conference> list = new ArrayList<>();
        final String sql = """
            SELECT * FROM conferences
            WHERE status = 'ACTIVE' AND event_date IS NOT NULL AND start_time IS NOT NULL
              AND day_before_reminder_sent_at IS NULL
        """;
        try (Connection conn = db.getConnection(); PreparedStatement ps = conn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery()) {
            while (rs.next()) list.add(map(conn, rs));
        } catch (SQLException e) { throw new RuntimeException(e); }
        return list;
    }

    private Conference map(final Connection conn, ResultSet rs) throws SQLException {
        double lat = rs.getDouble("latitude");
        Double latitude = rs.wasNull() ? null : lat;
        double lng = rs.getDouble("longitude");
        Double longitude = rs.wasNull() ? null : lng;
        final Conference conference = new Conference(
            rs.getString("uuid"), rs.getString("friendly_id"), rs.getString("name"),
            rs.getString("created_by_user_uuid"),
            ConferenceStatus.valueOf(rs.getString("status")),
            parseInstant(rs.getString("created_at")), parseInstant(rs.getString("updated_at")),
            parseInstantNullable(rs.getString("expires_at")),
            latitude, longitude,
            rs.getString("event_date"), rs.getString("venue")
        );
        conference.setStartTime(rs.getString("start_time"));
        conference.setEndTime(rs.getString("end_time"));
        conference.setNameAutoGenerated(rs.getInt("name_auto_generated") != 0);
        conference.setPresentationSourceUrl(rs.getString("presentation_source_url"));
        conference.setFlyerBase64(rs.getString("flyer_base64"));
        conference.setDescription(rs.getString("description"));
        conference.setVisibility(rs.getString("visibility"));
        conference.setScheduleMarkdown(rs.getString("schedule_markdown"));
        conference.setScheduleLayout(rs.getString("schedule_layout"));
        conference.setPublicTheme(rs.getString("public_theme"));
        conference.setTicketPrice(rs.getString("ticket_price"));
        conference.setTicketCurrency(rs.getString("ticket_currency"));
        conference.setTicketSalesEnabled(rs.getInt("ticket_sales_enabled") != 0);
        conference.setCertificateEngine(rs.getString("certificate_engine"));
        conference.setOnDemandVideoProvider(rs.getString("on_demand_video_provider"));
        conference.setOnDemandVideoUrl(rs.getString("on_demand_video_url"));
        final int timezoneId = rs.getInt("timezone_id");
        conference.setTimezoneId(rs.wasNull() ? null : timezoneId);
        conference.setReminderSentAt(parseInstantNullable(rs.getString("reminder_sent_at")));
        conference.setDayBeforeReminderSentAt(parseInstantNullable(rs.getString("day_before_reminder_sent_at")));
        conference.setSeatingMode(rs.getString("seating_mode") != null ? rs.getString("seating_mode") : "NONE");
        final int capacity = rs.getInt("capacity");
        conference.setCapacity(rs.wasNull() ? null : capacity);
        conference.setReservedCount(rs.getInt("reserved_count"));
        conference.setVenueMapBase64(rs.getString("venue_map_base64"));
        final String eventTypeKey = rs.getString("event_type_key");
        conference.setEventTypeKey(eventTypeKey != null ? eventTypeKey : "conference");
        conference.setNotesPurgedAt(parseInstantNullable(rs.getString("notes_purged_at")));
        conference.restoreDiagram(rs.getString("diagram_xml"), rs.getString("diagram_published_svg"),
                parseInstantNullable(rs.getString("diagram_updated_at")), rs.getLong("diagram_version"));
        conference.setDiagramPurgedAt(parseInstantNullable(rs.getString("diagram_purged_at")));
        conference.restoreWhiteboard(rs.getString("whiteboard_scene_json"), rs.getString("whiteboard_published_svg"),
                parseInstantNullable(rs.getString("whiteboard_updated_at")), rs.getLong("whiteboard_version"));
        conference.setSandboxVariant(rs.getString("sandbox_variant"));
        final int sandboxPoolSize = rs.getInt("sandbox_pool_size");
        conference.setSandboxPoolSize(rs.wasNull() ? null : sandboxPoolSize);
        conference.setSandboxInternetEnabled(rs.getInt("sandbox_internet_enabled"));
        conference.setSandboxRemoteGitUrl(rs.getString("sandbox_remote_git_url"));
        final int sandboxJvmHeapMb = rs.getInt("sandbox_jvm_heap_mb");
        conference.setSandboxJvmHeapMb(rs.wasNull() ? null : sandboxJvmHeapMb);
        final int sandboxSeatsPerPod = rs.getInt("sandbox_seats_per_pod");
        conference.setSandboxSeatsPerPod(rs.wasNull() ? null : sandboxSeatsPerPod);
        final int sandboxCliPoolSize = rs.getInt("sandbox_cli_pool_size");
        conference.setSandboxCliPoolSize(rs.wasNull() ? null : sandboxCliPoolSize);
        final int sandboxCliLazyVimPoolSize = rs.getInt("sandbox_cli_lazyvim_pool_size");
        conference.setSandboxCliLazyVimPoolSize(rs.wasNull() ? null : sandboxCliLazyVimPoolSize);
        final int maxDevicesPerUser = rs.getInt("max_devices_per_user");
        conference.setMaxDevicesPerUser(rs.wasNull() ? null : maxDevicesPerUser);
        final int maxAccountsPerDevice = rs.getInt("max_accounts_per_device");
        conference.setMaxAccountsPerDevice(rs.wasNull() ? null : maxAccountsPerDevice);
        conference.setCanvasTool(rs.getString("canvas_tool"));
        conference.setCanvasAudienceMode(normalizeCanvasMode(
                conference.getCanvasTool(), rs.getString("canvas_audience_mode")));
        final List<CanvasConfig> configs = new ArrayList<>();
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT canvas_tool, audience_mode FROM conference_canvas_configs "
                        + "WHERE conference_uuid = ? ORDER BY canvas_tool")) {
            ps.setString(1, conference.getUuid());
            try (ResultSet configRs = ps.executeQuery()) {
                while (configRs.next()) {
                    final String tool = configRs.getString("canvas_tool");
                    configs.add(new CanvasConfig(tool,
                            normalizeCanvasMode(tool, configRs.getString("audience_mode"))));
                }
            }
        }
        // Fallback para bases que todavía no ejecutaron la migración de filas hijas.
        if (configs.isEmpty() && conference.getCanvasTool() != null) {
            configs.add(new CanvasConfig(conference.getCanvasTool(),
                    normalizeCanvasMode(conference.getCanvasTool(), conference.getCanvasAudienceMode())));
        }
        conference.setCanvasConfigs(configs);
        final List<OnDemandCuePoint> cuePoints = new ArrayList<>();
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT at_seconds, label, tool_path FROM conference_on_demand_cue_points "
                        + "WHERE conference_uuid = ? ORDER BY sort_order")) {
            ps.setString(1, conference.getUuid());
            try (ResultSet cueRs = ps.executeQuery()) {
                while (cueRs.next()) {
                    cuePoints.add(new OnDemandCuePoint(cueRs.getInt("at_seconds"),
                            cueRs.getString("label"), cueRs.getString("tool_path")));
                }
            }
        }
        conference.setOnDemandCuePoints(cuePoints);
        return conference;
    }

    private static String normalizeCanvasMode(final String tool, final String mode) {
        if ("ETHERPAD".equals(tool)) {
            return "INDEPENDENT".equals(mode) ? "INDEPENDENT" : "COLLABORATIVE";
        }
        return "MODERATOR_ONLY".equals(mode) ? "MODERATOR_ONLY" : "INDEPENDENT";
    }

    @Override
    public List<Conference> findPendingNotesPurge() {
        final List<Conference> list = new ArrayList<>();
        final String sql = """
            SELECT * FROM conferences
            WHERE event_date IS NOT NULL AND end_time IS NOT NULL AND notes_purged_at IS NULL
        """;
        try (Connection conn = db.getConnection(); PreparedStatement ps = conn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery()) {
            while (rs.next()) list.add(map(conn, rs));
        } catch (SQLException e) { throw new RuntimeException(e); }
        return list;
    }

    @Override
    public List<Conference> findPendingDiagramPurge() {
        final List<Conference> list = new ArrayList<>();
        final String sql = """
            SELECT * FROM conferences
            WHERE event_date IS NOT NULL AND end_time IS NOT NULL AND diagram_purged_at IS NULL
              AND diagram_xml IS NOT NULL
        """;
        try (Connection conn = db.getConnection(); PreparedStatement ps = conn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery()) {
            while (rs.next()) list.add(map(conn, rs));
        } catch (SQLException e) { throw new RuntimeException(e); }
        return list;
    }

    @Override
    public boolean tryIncrementReservedCount(String conferenceUuid) {
        final String sql = "UPDATE conferences SET reserved_count = reserved_count + 1 "
                + "WHERE uuid = ? AND capacity IS NOT NULL AND reserved_count < capacity";
        try (Connection conn = db.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, conferenceUuid);
            return ps.executeUpdate() == 1;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public void decrementReservedCount(String conferenceUuid) {
        final String sql = "UPDATE conferences SET reserved_count = MAX(0, reserved_count - 1) WHERE uuid = ?";
        try (Connection conn = db.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, conferenceUuid);
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    private Optional<Conference> query(String sql, String param) {
        try (Connection conn = db.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, param);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) return Optional.of(map(conn, rs));
        } catch (SQLException e) { throw new RuntimeException(e); }
        return Optional.empty();
    }

    private static Instant parseInstant(String s) {
        if (s == null) return Instant.now();
        String iso = s.contains("T") ? s : s.replace(" ", "T") + "Z";
        return Instant.parse(iso);
    }

    private static Instant parseInstantNullable(String s) {
        if (s == null || s.isBlank()) return null;
        String iso = s.contains("T") ? s : s.replace(" ", "T") + "Z";
        return Instant.parse(iso);
    }
}
