package dev.rafex.insightbloom.users.adapters.outbound.sqlite;

import dev.rafex.insightbloom.users.domain.model.Conference;
import dev.rafex.insightbloom.users.domain.model.ConferenceStatus;
import dev.rafex.insightbloom.users.domain.ports.ConferenceRepository;

import java.sql.*;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class SqliteConferenceRepository implements ConferenceRepository {
    private final DatabaseManager db;

    public SqliteConferenceRepository(DatabaseManager db) {
        this.db = db;
    }

    @Override
    public void save(Conference conference) {
        String sql = """
            INSERT OR REPLACE INTO conferences
              (uuid, friendly_id, name, created_by_user_uuid, status, created_at, updated_at, expires_at, latitude, longitude, event_date, venue, start_time, end_time, name_auto_generated, presentation_source_url, flyer_base64, timezone_id, reminder_sent_at, seating_mode, capacity, reserved_count, venue_map_base64, event_type_key, notes_purged_at, diagram_xml, diagram_updated_at, diagram_purged_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """;
        try (Connection conn = db.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, conference.getUuid());
            ps.setString(2, conference.getFriendlyId());
            ps.setString(3, conference.getName());
            ps.setString(4, conference.getCreatedByUserUuid());
            ps.setString(5, conference.getStatus().name());
            ps.setString(6, conference.getCreatedAt().toString());
            ps.setString(7, conference.getUpdatedAt().toString());
            ps.setString(8, conference.getExpiresAt() != null ? conference.getExpiresAt().toString() : null);
            if (conference.getLatitude() != null) ps.setDouble(9, conference.getLatitude());
            else ps.setNull(9, Types.REAL);
            if (conference.getLongitude() != null) ps.setDouble(10, conference.getLongitude());
            else ps.setNull(10, Types.REAL);
            ps.setString(11, conference.getEventDate());
            ps.setString(12, conference.getVenue());
            ps.setString(13, conference.getStartTime());
            ps.setString(14, conference.getEndTime());
            ps.setInt(15, conference.isNameAutoGenerated() ? 1 : 0);
            ps.setString(16, conference.getPresentationSourceUrl());
            ps.setString(17, conference.getFlyerBase64());
            if (conference.getTimezoneId() != null) ps.setInt(18, conference.getTimezoneId());
            else ps.setNull(18, Types.INTEGER);
            ps.setString(19, conference.getReminderSentAt() != null ? conference.getReminderSentAt().toString() : null);
            ps.setString(20, conference.getSeatingMode());
            if (conference.getCapacity() != null) ps.setInt(21, conference.getCapacity());
            else ps.setNull(21, Types.INTEGER);
            ps.setInt(22, conference.getReservedCount());
            ps.setString(23, conference.getVenueMapBase64());
            ps.setString(24, conference.getEventTypeKey());
            ps.setString(25, conference.getNotesPurgedAt() != null ? conference.getNotesPurgedAt().toString() : null);
            ps.setString(26, conference.getDiagramXml());
            ps.setString(27, conference.getDiagramUpdatedAt() != null ? conference.getDiagramUpdatedAt().toString() : null);
            ps.setString(28, conference.getDiagramPurgedAt() != null ? conference.getDiagramPurgedAt().toString() : null);
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public void delete(String uuid) {
        String sql = "DELETE FROM conferences WHERE uuid = ?";
        try (Connection conn = db.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, uuid);
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public Optional<Conference> findByUuid(String uuid) {
        return query("SELECT * FROM conferences WHERE uuid = ?", uuid);
    }

    @Override
    public Optional<Conference> findByFriendlyId(String friendlyId) {
        return query("SELECT * FROM conferences WHERE friendly_id = ?", friendlyId);
    }

    @Override
    public Optional<Conference> findByShortCode(String shortCode) {
        // Últimos 7 hex chars del UUID (sin guiones): e.g. "b338a5a" de "...b95e3b338a5a"
        return query(
            "SELECT * FROM conferences WHERE LOWER(SUBSTR(REPLACE(uuid,'-',''), -7)) = LOWER(?)",
            shortCode
        );
    }

    @Override
    public boolean existsByFriendlyId(String friendlyId) {
        String sql = "SELECT 1 FROM conferences WHERE friendly_id = ?";
        try (Connection conn = db.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, friendlyId);
            return ps.executeQuery().next();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public List<Conference> findByUser(String userUuid) {
        List<Conference> list = new ArrayList<>();
        String sql = "SELECT * FROM conferences WHERE created_by_user_uuid = ? ORDER BY created_at DESC";
        try (Connection conn = db.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, userUuid);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) list.add(map(rs));
        } catch (SQLException e) { throw new RuntimeException(e); }
        return list;
    }

    @Override
    public List<Conference> findPendingReminder() {
        final List<Conference> list = new ArrayList<>();
        final String sql = """
            SELECT * FROM conferences
            WHERE status = 'ACTIVE' AND event_date IS NOT NULL AND start_time IS NOT NULL
              AND reminder_sent_at IS NULL
        """;
        try (Connection conn = db.getConnection(); PreparedStatement ps = conn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery()) {
            while (rs.next()) list.add(map(rs));
        } catch (SQLException e) { throw new RuntimeException(e); }
        return list;
    }

    private Conference map(ResultSet rs) throws SQLException {
        double lat = rs.getDouble("latitude");
        Double latitude = rs.wasNull() ? null : lat;
        double lng = rs.getDouble("longitude");
        Double longitude = rs.wasNull() ? null : lng;
        final Conference conference = new Conference(
            rs.getString("uuid"), rs.getString("friendly_id"), rs.getString("name"),
            rs.getString("created_by_user_uuid"),
            ConferenceStatus.valueOf(rs.getString("status")),
            parseInstant(rs.getString("created_at")), parseInstant(rs.getString("updated_at")),
            parseInstantNullable(rs.getString("expires_at")),
            latitude, longitude,
            rs.getString("event_date"), rs.getString("venue")
        );
        conference.setStartTime(rs.getString("start_time"));
        conference.setEndTime(rs.getString("end_time"));
        conference.setNameAutoGenerated(rs.getInt("name_auto_generated") != 0);
        conference.setPresentationSourceUrl(rs.getString("presentation_source_url"));
        conference.setFlyerBase64(rs.getString("flyer_base64"));
        final int timezoneId = rs.getInt("timezone_id");
        conference.setTimezoneId(rs.wasNull() ? null : timezoneId);
        conference.setReminderSentAt(parseInstantNullable(rs.getString("reminder_sent_at")));
        conference.setSeatingMode(rs.getString("seating_mode") != null ? rs.getString("seating_mode") : "NONE");
        final int capacity = rs.getInt("capacity");
        conference.setCapacity(rs.wasNull() ? null : capacity);
        conference.setReservedCount(rs.getInt("reserved_count"));
        conference.setVenueMapBase64(rs.getString("venue_map_base64"));
        final String eventTypeKey = rs.getString("event_type_key");
        conference.setEventTypeKey(eventTypeKey != null ? eventTypeKey : "conference");
        conference.setNotesPurgedAt(parseInstantNullable(rs.getString("notes_purged_at")));
        conference.restoreDiagramXml(rs.getString("diagram_xml"), parseInstantNullable(rs.getString("diagram_updated_at")));
        conference.setDiagramPurgedAt(parseInstantNullable(rs.getString("diagram_purged_at")));
        return conference;
    }

    @Override
    public List<Conference> findPendingNotesPurge() {
        final List<Conference> list = new ArrayList<>();
        final String sql = """
            SELECT * FROM conferences
            WHERE event_date IS NOT NULL AND end_time IS NOT NULL AND notes_purged_at IS NULL
        """;
        try (Connection conn = db.getConnection(); PreparedStatement ps = conn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery()) {
            while (rs.next()) list.add(map(rs));
        } catch (SQLException e) { throw new RuntimeException(e); }
        return list;
    }

    @Override
    public List<Conference> findPendingDiagramPurge() {
        final List<Conference> list = new ArrayList<>();
        final String sql = """
            SELECT * FROM conferences
            WHERE event_date IS NOT NULL AND end_time IS NOT NULL AND diagram_purged_at IS NULL
              AND diagram_xml IS NOT NULL
        """;
        try (Connection conn = db.getConnection(); PreparedStatement ps = conn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery()) {
            while (rs.next()) list.add(map(rs));
        } catch (SQLException e) { throw new RuntimeException(e); }
        return list;
    }

    @Override
    public boolean tryIncrementReservedCount(String conferenceUuid) {
        final String sql = "UPDATE conferences SET reserved_count = reserved_count + 1 "
                + "WHERE uuid = ? AND capacity IS NOT NULL AND reserved_count < capacity";
        try (Connection conn = db.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, conferenceUuid);
            return ps.executeUpdate() == 1;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public void decrementReservedCount(String conferenceUuid) {
        final String sql = "UPDATE conferences SET reserved_count = MAX(0, reserved_count - 1) WHERE uuid = ?";
        try (Connection conn = db.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, conferenceUuid);
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    private Optional<Conference> query(String sql, String param) {
        try (Connection conn = db.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, param);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) return Optional.of(map(rs));
        } catch (SQLException e) { throw new RuntimeException(e); }
        return Optional.empty();
    }

    private static Instant parseInstant(String s) {
        if (s == null) return Instant.now();
        String iso = s.contains("T") ? s : s.replace(" ", "T") + "Z";
        return Instant.parse(iso);
    }

    private static Instant parseInstantNullable(String s) {
        if (s == null || s.isBlank()) return null;
        String iso = s.contains("T") ? s : s.replace(" ", "T") + "Z";
        return Instant.parse(iso);
    }
}
