export interface Timezone {
  id: number
  ianaName: string
  label: string
  utcOffsetMinutes: number
  isDefault: boolean
}

export interface Conference {
  uuid: string
  friendlyId: string
  name: string
  displayName?: string | null
  nameAutoGenerated?: boolean
  venue?: string | null
  eventDate?: string | null
  startTime?: string | null
  endTime?: string | null
  latitude?: number | null
  longitude?: number | null
  presentationSourceUrl?: string | null
  flyerBase64?: string | null
  timezoneId?: number | null
  expiresAt?: string | null
  [key: string]: unknown
}

export interface ConferenceHistoryEntry {
  conferenceUuid: string
  friendlyId?: string
  name?: string
  joinedAt: string
  available: boolean
}

export interface UpdateConferenceRequest {
  displayName?: string | null
  venue?: string | null
  eventDate?: string | null
  startTime?: string | null
  endTime?: string | null
  latitude?: number | null
  longitude?: number | null
  presentationSourceUrl?: string | null
  flyerBase64?: string | null
  timezoneId?: number | null
}

export interface DownloadCounts {
  certificate: number
  presentation: number
}

export interface CertificateSettings {
  [key: string]: unknown
}

export interface UserProfile {
  uuid: string
  displayName?: string | null
  firstName?: string | null
  lastName?: string | null
  email?: string | null
  phone?: string | null
  [key: string]: unknown
}
