export interface Timezone {
  id: number
  ianaName: string
  label: string
  utcOffsetMinutes: number
  isDefault: boolean
}

export type SeatingMode = 'NONE' | 'GENERAL' | 'SEATED'

export type CanvasTool = 'DRAWIO' | 'EXCALIDRAW' | 'ETHERPAD'
export type CanvasAudienceMode = 'INDEPENDENT' | 'MODERATOR_ONLY' | 'COLLABORATIVE'
export type CertificateEngine = 'INHOUSE' | 'HTML_CHROME'
export type EventVisibility = 'PRIVATE' | 'PUBLIC' | 'HYBRID'
export type PublicTheme = 'CLASSIC' | 'EDITORIAL' | 'MINIMAL'
export interface CanvasToolConfig {
  tool: CanvasTool
  audienceMode: CanvasAudienceMode
}

export type EventCapability =
  | 'TICKETING_GENERAL' | 'TICKETING_SEATED' | 'SURVEY' | 'PRESENTATION' | 'WORD_CLOUD'
  | 'CHAT_BOT' | 'VIDEO_CONFERENCE' | 'WHITEBOARD' | 'DIAGRAMMING' | 'COLLAB_NOTES' | 'CODE_IDE'

export interface IntegrationConfig {
  drawioBaseUrl?: string | null
  etherpadBaseUrl?: string | null
  jaasAppId?: string | null
  excalidrawBaseUrl?: string | null
}

export interface JaasToken {
  token: string
  appId: string
  roomName: string
  sessionUuid?: string | null
  revokedDeviceFingerprints?: string[]
}

export interface JaasUsage {
  month: string
  uniqueParticipants: number
  monthlyLimit: number
  remaining: number
  percentage: number
  bandwidthLimitGb: number
  bandwidthUsedGb?: number | null
}

export interface JitsiInviteAccess {
  allowed: boolean
  conferenceId: string
  friendlyId: string
  ticketRequired: boolean
}

export interface EventNotesPad {
  padId: string
}

export type RoleScopeValue = 'PLATFORM' | 'EVENT'

export type PermissionValue =
  | 'MANAGE_USERS' | 'MANAGE_EVENT_TYPES' | 'HOST_EVENT' | 'MANAGE_EVENT_SETTINGS'
  | 'ASSIGN_EVENT_ROLES' | 'MODERATE_CONTENT' | 'CHECK_IN' | 'MANAGE_PRESENTATION'
  | 'MANAGE_TICKETS' | 'MANAGE_SURVEY' | 'MANAGE_CERTIFICATE' | 'VIDEO_MODERATE'

export interface Role {
  uuid: string
  key: string
  name: string
  description?: string | null
  scope: RoleScopeValue
  permissions: PermissionValue[]
  active: boolean
}

export interface EventRoleAssignment {
  userUuid: string
  displayName?: string | null
  email?: string | null
  roleKey: string
  assignedAt: string
}

export interface EventType {
  uuid: string
  key: string
  name: string
  description?: string | null
  capabilities: EventCapability[]
  active: boolean
}

export interface Conference {
  uuid: string
  status?: 'ACTIVE' | 'CLOSED' | string
  createdByUserUuid?: string
  friendlyId: string
  name: string
  displayName?: string | null
  nameAutoGenerated?: boolean
  venue?: string | null
  eventDate?: string | null
  startTime?: string | null
  endTime?: string | null
  latitude?: number | null
  longitude?: number | null
  presentationSourceUrl?: string | null
  flyerBase64?: string | null
  description?: string | null
  visibility?: EventVisibility
  scheduleMarkdown?: string | null
  scheduleLayout?: 'LEFT' | 'RIGHT'
  publicTheme?: PublicTheme
  timezoneId?: number | null
  expiresAt?: string | null
  seatingMode?: SeatingMode
  capacity?: number | null
  reservedCount?: number
  ticketPrice?: string | null
  ticketCurrency?: string | null
  ticketSalesEnabled?: boolean
  venueMapBase64?: string | null
  eventTypeKey?: string
  sandboxVariant?: string | null
  sandboxPoolSize?: number | null
  sandboxInternetEnabled?: number | null
  sandboxExtraPackages?: string | null
  sandboxRemoteGitUrl?: string | null
  canvasTool?: CanvasTool | null
  canvasAudienceMode?: CanvasAudienceMode | null
  canvasConfigs?: CanvasToolConfig[]
  certificateEngine?: CertificateEngine
  sandboxJvmHeapMb?: number | null
  sandboxSeatsPerPod?: number | null
  sandboxCliPoolSize?: number | null
  maxDevicesPerUser?: number | null
  maxAccountsPerDevice?: number | null
  [key: string]: unknown
}

export interface PublicConference {
  friendlyId: string
  name: string
  description?: string | null
  organizer: string
  eventDate?: string | null
  startTime?: string | null
  endTime?: string | null
  venue?: string | null
  latitude?: number | null
  longitude?: number | null
  capacity?: number | null
  remainingSeats?: number | null
  ticketPrice?: string | null
  ticketCurrency?: string | null
  ticketRequired: boolean
  ticketPurchaseEnabled: boolean
  visibility: EventVisibility
  flyerBase64?: string | null
  scheduleMarkdown?: string | null
  scheduleLayout?: 'LEFT' | 'RIGHT'
  publicTheme?: PublicTheme
  organizerPhotoBase64?: string | null
  /** True only for the current authenticated user; no ticket data is exposed. */
  hasTicket?: boolean
}

// Fase C (DEC-0025): asiento de un Pod "neovim" compartido que el watchdog del seat-agent tuvo
// que terminar por abuso de recursos -- ver ListSandboxIncidentsUseCase.
export interface SandboxIncident {
  uuid: string
  conferenceUuid: string
  podName: string
  seatIndex: number
  userUuid: string | null
  type: string
  detail: string | null
  occurredAt: string
}

// Dispositivo bloqueado en una conferencia por superar maxAccountsPerDevice (demasiadas cuentas
// distintas desde el mismo fingerprint) -- ver DeviceAccessGuard. unblockedAt null = sigue activo.
export interface DeviceBlock {
  uuid: string
  conferenceUuid: string
  deviceFingerprint: string
  accountCount: number
  blockedAt: string
  unblockedAt: string | null
  unblockedBy: string | null
}

// Umbrales de PlatformDeviceGuard -- alcance plataforma, no un evento puntual (ver DeviceBlock,
// que es el equivalente por conferencia).
export interface DeviceAccessSettings {
  maxAccountsPerDevice: number | null
  maxSessionsPerUser: number | null
  maxRegistrationsPerDevicePerDay: number | null
}

export interface ConferenceAccess {
  eventActive?: boolean
  eventStatus?: 'ACTIVE' | 'CLOSED' | string
  ticketRequired: boolean
  hasAccess: boolean
  presentationAccess: boolean
  publicOnly: boolean
  publicAreas: string[]
  privateAreas: string[]
  previewSlideLimit: number
}

// Dispositivo bloqueado a nivel PLATAFORMA por PlatformDeviceGuard (multicuenta entre eventos o
// spam de registro) -- distinto de DeviceBlock, que es por conferencia.
export interface PlatformDeviceBlock {
  uuid: string
  deviceFingerprint: string
  reason: 'MULTI_ACCOUNT' | 'REGISTRATION_SPAM'
  relatedCount: number
  blockedAt: string
  unblockedAt: string | null
  unblockedBy: string | null
}

// Discrepancia de fingerprint detectada DENTRO de una sesion ya logueada (el fingerprint que
// llego en un request no coincide con el del login) -- ver DeviceFingerprintAuditor. Nunca
// implica que la sesion se cortó; es pura visibilidad para revisión de un admin.
export interface DeviceFingerprintFlag {
  uuid: string
  subjectUuid: string
  subjectKind: 'user' | 'guest'
  loginFingerprint: string
  lastSeenFingerprint: string
  occurrenceCount: number
  firstSeenAt: string
  lastSeenAt: string
  reviewedAt: string | null
  reviewedBy: string | null
}

export type ReservationStatus = 'RESERVED' | 'CHECKED_IN'

export interface Reservation {
  uuid: string
  conferenceUuid: string
  userUuid: string
  seatUuid?: string | null
  operational: boolean
  ticketCode: string
  status: ReservationStatus
  createdAt: string
  checkedInAt?: string | null
}

export type TicketStatus = 'ISSUED' | 'CLAIMED' | 'CHECKED_IN' | 'REVOKED' | 'EXPIRED'

export interface Ticket {
  uuid: string
  conferenceUuid: string
  ticketCode: string
  issuedByUserUuid: string
  recipientEmail?: string | null
  seatUuid?: string | null
  status: TicketStatus
  claimedByUserUuid?: string | null
  issuedAt: string
  claimedAt?: string | null
  checkedInAt?: string | null
  revokedByUserUuid?: string | null
  revokedAt?: string | null
  operational?: boolean
}

export interface TicketClaimedUser {
  uuid: string
  displayName?: string | null
  username?: string | null
  email?: string | null
}

export interface TicketManagementSummary {
  capacity?: number | null
  reservedCount: number
  remainingToIssue?: number | null
  tickets: Ticket[]
  claimedUsers: Record<string, TicketClaimedUser>
}

export interface VenueSeat {
  uuid: string
  label: string
  x: number
  y: number
  occupied: boolean
}

export interface ConferenceHistoryEntry {
  conferenceUuid: string
  friendlyId?: string
  name?: string
  joinedAt: string
  available: boolean
  seatingMode?: SeatingMode
}

export interface UpdateConferenceRequest {
  displayName?: string | null
  venue?: string | null
  eventDate?: string | null
  startTime?: string | null
  endTime?: string | null
  latitude?: number | null
  longitude?: number | null
  presentationSourceUrl?: string | null
  flyerBase64?: string | null
  timezoneId?: number | null
  description?: string | null
  visibility?: EventVisibility
  scheduleMarkdown?: string | null
  scheduleLayout?: 'LEFT' | 'RIGHT'
  publicTheme?: PublicTheme
  ticketPrice?: string | null
  ticketCurrency?: string | null
}

export interface DownloadCounts {
  certificate: number
  presentation: number
}

export interface CertificateSettings {
  logoBase64?: string
  fontFamily?: string
  titleFontSize?: number
  bodyFontSize?: number
  primaryColorHex?: string
  showVenue?: boolean
  showSchedule?: boolean
  showIssuedDate?: boolean
  [key: string]: unknown
}

export interface CertificateTemplateVariable {
  key: string
  label: string
  example: string
}

export interface CertificateTemplateCatalogItem {
  key: string
  name: string
  description: string
  engine: CertificateEngine
  documentJson: string
}

export interface CertificateTemplate {
  conferenceUuid: string
  templateKey: string
  templateName: string
  engine: CertificateEngine
  documentJson: string
  version: number
  updatedAt?: string
}

export interface CertificateTemplateCatalog {
  templates: CertificateTemplateCatalogItem[]
  variables: CertificateTemplateVariable[]
}

export interface UserProfile {
  uuid: string
  displayName?: string | null
  firstName?: string | null
  lastName?: string | null
  email?: string | null
  phone?: string | null
  publicProfilePhotoBase64?: string | null
  [key: string]: unknown
}

export type SandboxStatus = 'PENDING' | 'READY'
export type SandboxVariant = 'web' | 'cli'

export interface SandboxInfo {
  sandboxUuid: string
  sandboxSlot: number
  variant: SandboxVariant
  status: SandboxStatus
  gatewayUrl: string
  sandboxPath: string
  expiresInSeconds?: number
}

export interface SandboxVariantAvailability {
  available: boolean
  activeCount: number
  capacity: number
}

export interface SandboxAvailability {
  web: SandboxVariantAvailability
  cli: SandboxVariantAvailability
}

export interface SandboxStatusSeat {
  seatIndex: number
  userUuid: string | null
  assignedAt: string | null
}

export interface SandboxStatusEntry {
  sandboxUuid: string
  podName: string
  variant: SandboxVariant
  phase: string
  ready: boolean
  seats: SandboxStatusSeat[]
}

export interface SandboxPrewarmVariantResult {
  variant: SandboxVariant
  desiredPods: number
  createdPods: number
}

export interface SandboxPrewarmResult {
  conferenceUuid: string
  variants: SandboxPrewarmVariantResult[]
}

export interface WorkspaceFileEntry {
  path: string
  isDirectory: boolean
  mtime: number
  sizeBytes: number
}

export interface WorkspaceFileContent {
  content: string
  mtime: number
}

export interface WorkspaceDownloadInfo {
  sandboxUuid: string
  downloadUrl: string
  expiresInSeconds: number
}

export interface WorkspacePreviewInfo {
  publicationId: string
  url: string
  expiresAt: string
  artifactHash: string
  files: number
}

export interface AiProviderSettings {
  configured: boolean
  enabled: boolean
  baseUrl: string
  model: string
  systemPrompt: string | null
  guardrails: string | null
  temperature: number | null
  apiKeyConfigured: boolean
  apiKeyHint: string | null
}

export interface AiSettings {
  providers: {
    chat: AiProviderSettings
    tutor: AiProviderSettings
    survey: AiProviderSettings
    seatLayout: AiProviderSettings
  }
  chatAiEnabled: boolean
  chatSystemPrompt: string | null
  chatGuardrails: string | null
  chatTemperature: number | null
  aiBaseUrl: string
  aiModel: string
  aiApiKeyConfigured: boolean
  aiApiKeyHint: string | null
}

export type ChatSettings = AiSettings

export interface AiPromptVariable {
  key: string
  label: string
  example: string
  autoIncludedIn: string
}
