export interface Timezone {
  id: number
  ianaName: string
  label: string
  utcOffsetMinutes: number
  isDefault: boolean
}

export type SeatingMode = 'NONE' | 'GENERAL' | 'SEATED'

export type EventCapability =
  | 'TICKETING_GENERAL' | 'TICKETING_SEATED' | 'SURVEY' | 'PRESENTATION' | 'WORD_CLOUD'
  | 'CHAT_BOT' | 'VIDEO_CONFERENCE' | 'WHITEBOARD' | 'DIAGRAMMING' | 'COLLAB_NOTES'

export interface IntegrationConfig {
  drawioBaseUrl?: string | null
}

export interface EventType {
  uuid: string
  key: string
  name: string
  description?: string | null
  capabilities: EventCapability[]
  active: boolean
}

export interface Conference {
  uuid: string
  friendlyId: string
  name: string
  displayName?: string | null
  nameAutoGenerated?: boolean
  venue?: string | null
  eventDate?: string | null
  startTime?: string | null
  endTime?: string | null
  latitude?: number | null
  longitude?: number | null
  presentationSourceUrl?: string | null
  flyerBase64?: string | null
  timezoneId?: number | null
  expiresAt?: string | null
  seatingMode?: SeatingMode
  capacity?: number | null
  reservedCount?: number
  venueMapBase64?: string | null
  eventTypeKey?: string
  [key: string]: unknown
}

export type ReservationStatus = 'RESERVED' | 'CHECKED_IN'

export interface Reservation {
  uuid: string
  conferenceUuid: string
  userUuid: string
  seatUuid?: string | null
  ticketCode: string
  status: ReservationStatus
  createdAt: string
  checkedInAt?: string | null
}

export interface VenueSeat {
  uuid: string
  label: string
  x: number
  y: number
  occupied: boolean
}

export interface ConferenceHistoryEntry {
  conferenceUuid: string
  friendlyId?: string
  name?: string
  joinedAt: string
  available: boolean
}

export interface UpdateConferenceRequest {
  displayName?: string | null
  venue?: string | null
  eventDate?: string | null
  startTime?: string | null
  endTime?: string | null
  latitude?: number | null
  longitude?: number | null
  presentationSourceUrl?: string | null
  flyerBase64?: string | null
  timezoneId?: number | null
}

export interface DownloadCounts {
  certificate: number
  presentation: number
}

export interface CertificateSettings {
  logoBase64?: string
  fontFamily?: string
  titleFontSize?: number
  bodyFontSize?: number
  primaryColorHex?: string
  showVenue?: boolean
  showSchedule?: boolean
  showIssuedDate?: boolean
  [key: string]: unknown
}

export interface UserProfile {
  uuid: string
  displayName?: string | null
  firstName?: string | null
  lastName?: string | null
  email?: string | null
  phone?: string | null
  [key: string]: unknown
}
