FROM node:25-alpine AS builder
WORKDIR /app
COPY frontend/web/package*.json ./
RUN npm install
COPY frontend/web/ .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY infra/docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
