package dev.rafex.insightbloom.users.domain.model;

import java.time.Instant;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.List;
import java.util.Locale;
import java.util.UUID;

public class Conference {
    private final String uuid;
    private final String friendlyId;
    private String name;
    private final String createdByUserUuid;
    private ConferenceStatus status;
    private final Instant createdAt;
    private Instant updatedAt;
    private Instant expiresAt; // nullable
    private Double latitude;
    private Double longitude;
    private String eventDate; // ISO-8601 date string, nullable
    private String venue; // nullable
    private String startTime; // HH:mm, nullable
    private String endTime; // HH:mm, nullable
    // true cuando el organizador no fijó un nombre de certificado explícito al crear/editar la
    // conferencia: permite que el título extraído del markdown de la presentación lo complete.
    private boolean nameAutoGenerated;
    private String presentationSourceUrl; // repo o descarga de la presentación, nullable
    // Video on-demand (tier gratuito): el organizador pega la URL de un video ya alojado en
    // YouTube o en un nodo publico de PeerTube -- sin storage/transcodificacion propia. La URL
    // se guarda tal cual la pega el organizador; la conversion a URL de embed vive en el
    // frontend (onDemandVideo.ts), no aca.
    private String onDemandVideoProvider; // "YOUTUBE" | "PEERTUBE", nullable
    private String onDemandVideoUrl; // nullable
    private String flyerBase64; // imagen promocional opcional (data URL), nullable
    private String description; // detalle público del evento, nullable
    private String visibility = "PRIVATE"; // PRIVATE | PUBLIC | HYBRID
    private String scheduleMarkdown; // cronograma opcional, authored as Markdown
    private String scheduleLayout = "RIGHT"; // LEFT | RIGHT
    // Preset visual de la cartelera pública. Solo controla presentación; el contenido sigue
    // viviendo en los campos del evento (description, flyer y scheduleMarkdown).
    private String publicTheme = "CLASSIC"; // CLASSIC | EDITORIAL | MINIMAL
    private Integer timezoneId; // FK a timezones, nullable (se resuelve al default si no se envía)
    private Instant reminderSentAt; // marca cuándo se envió el recordatorio de 1h antes, nullable
    private Instant dayBeforeReminderSentAt; // marca cuándo se envió el recordatorio de 1 día antes, nullable
    private String seatingMode = "NONE"; // NONE | GENERAL | SEATED
    private Integer capacity; // aforo máximo, solo relevante en modo GENERAL
    private int reservedCount; // contador atómico de reservas activas en modo GENERAL
    // Precio en unidades mayores. Se conserva como texto decimal para no introducir errores de
    // punto flotante y dejar el modelo listo para un proveedor de pagos posterior.
    private String ticketPrice = "0.00";
    private String ticketCurrency = "MXN";
    // Cierra la emisión pública sin desactivar el evento ni revocar boletos existentes.
    private boolean ticketSalesEnabled = true;
    private String venueMapBase64; // imagen del recinto (data URL) para modo SEATED, nullable
    private String eventTypeKey = "conference"; // FK a event_types.key; toda conferencia existente cae aquí
    private Instant notesPurgedAt; // marca cuándo se borró el pad de Etherpad (TTL, ver DEC-0020), nullable
    private String diagramXml; // ultimo XML guardado del diagrama de drawio, nullable
    private String diagramPublishedSvg; // ultima exportacion SVG publicada para asistentes, nullable
    private Instant diagramUpdatedAt; // nullable
    private long diagramVersion;
    private Instant diagramPurgedAt; // marca cuándo se purgó el diagrama por TTL, nullable
    private String whiteboardSceneJson; // ultima escena nativa de Excalidraw del moderador
    private String whiteboardPublishedSvg; // ultima exportacion SVG publicada para asistentes
    private Instant whiteboardUpdatedAt;
    private long whiteboardVersion;
    // Vestigial (2026-07, pools Web/CLI independientes): ya no selecciona "la" variante -- las
    // dos conviven siempre para toda conferencia con CODE_IDE habilitada, cada una con su propio
    // pool (sandboxPoolSize=web, sandboxCliPoolSize=cli). Se deja la columna sin borrar (evita
    // una migracion innecesaria) solo por compatibilidad de lectura de filas viejas.
    private String sandboxVariant; // python|java|web, solo si CODE_IDE habilitada, nullable
    private Integer sandboxPoolSize; // tamaño del pool "web" (code-server) de sandboxes, nullable
    // Tamaño del pool "cli" (terminal-nvim, reusable/multi-asiento) -- independiente del pool
    // "web" de arriba (ver AssignSandboxUseCase). Nullable, default efectivo 1 si no se
    // configura (mismo patron que sandboxPoolSize).
    private Integer sandboxCliPoolSize;
    // Tamaño del pool CLI basado en LazyVim. Es independiente del pool CLI estable para que
    // cada asistente pueda elegir su distribución sin mezclar Pods ni workspaces.
    private Integer sandboxCliLazyVimPoolSize;
    private Integer sandboxInternetEnabled; // 0|1, por defecto 0
    private String sandboxRemoteGitUrl; // URL de remoto git del profesor, nullable
    // Heap maximo (-Xmx, en MB) de las JVMs dentro del sandbox (jdt.ls, java/mvn que corra el
    // alumno) -- nullable, si no se configura se usa un default chico pensado para cursos
    // (ver KubernetesPodClient). Clampeado contra el limite de memoria del contenedor
    // (SANDBOX_DEBIAN_MEMORY_LIMIT/SANDBOX_NEOVIM_MEMORY_LIMIT, ver SetSandboxConfigUseCase) --
    // nunca puede exceder ese techo, para que un heap mal configurado no tire el contenedor por OOM.
    private Integer sandboxJvmHeapMb;
    // Cantidad de alumnos que comparten UN mismo Pod "neovim" (varios usuarios Linux dentro del
    // mismo contenedor, cada uno con su propio home/ttyd) -- nullable, default efectivo 4 si no
    // se configura (ver AssignSandboxUseCase). Solo tiene efecto en modo terminal-nvim; en modo
    // debian se ignora (code-server no se puede compartir entre alumnos). Validado 1..10 en
    // SetSandboxConfigUseCase -- un numero mas alto exigiria revisar el LimitRange del namespace
    // a mano, no es un simple ajuste de config.
    private Integer sandboxSeatsPerPod;
    // Control de acceso por dispositivo (2026-07, ver DeviceAccessGuard): cuántos dispositivos
    // distintos puede tener activos a la vez un mismo usuario en Jitsi/IDE dentro de ESTE evento,
    // y cuántas cuentas distintas puede compartir un mismo dispositivo antes de bloquearlo.
    // Nullable, defaults efectivos en DeviceAccessGuard (2 y 3 respectivamente) si no se configura.
    private Integer maxDevicesPerUser;
    private Integer maxAccountsPerDevice;
    // Configuracion legacy del lienzo. Se conserva para compatibilidad con clientes y filas
    // antiguas; las configuraciones nuevas viven en canvasConfigs, una por herramienta.
    private CanvasTool canvasTool; // null cuando hay 0 o varias herramientas (legacy/all)
    private CanvasAudienceMode canvasAudienceMode; // null cuando hay 0 o varias herramientas (legacy)
    private List<CanvasConfig> canvasConfigs = List.of();
    // Sugerencias de herramienta por timestamp del video on-demand (opcional). Vive en tabla hija
    // propia, mismo patron que canvasConfigs.
    private List<OnDemandCuePoint> onDemandCuePoints = List.of();
    // INHOUSE conserva PDFBox; HTML_CHROME usa la plantilla visual con Playwright + Chromium.
    private String certificateEngine = "INHOUSE";

    public Conference(String friendlyId, String name, String createdByUserUuid) {
        this.uuid = UUID.randomUUID().toString();
        this.friendlyId = friendlyId;
        this.name = name;
        this.createdByUserUuid = createdByUserUuid;
        this.status = ConferenceStatus.ACTIVE;
        this.createdAt = Instant.now();
        this.updatedAt = this.createdAt;
    }

    public Conference(String friendlyId, String name, String createdByUserUuid, Double latitude, Double longitude) {
        this(friendlyId, name, createdByUserUuid);
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public Conference(String friendlyId, String name, String createdByUserUuid, Instant expiresAt) {
        this(friendlyId, name, createdByUserUuid);
        this.expiresAt = expiresAt;
    }

    public Conference(String friendlyId, String name, String createdByUserUuid, Instant expiresAt, Double latitude, Double longitude) {
        this(friendlyId, name, createdByUserUuid);
        this.expiresAt = expiresAt;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public Conference(String uuid, String friendlyId, String name, String createdByUserUuid,
                      ConferenceStatus status, Instant createdAt, Instant updatedAt,
                      Instant expiresAt, Double latitude, Double longitude) {
        this(uuid, friendlyId, name, createdByUserUuid, status, createdAt, updatedAt,
                expiresAt, latitude, longitude, null, null);
    }

    public Conference(String uuid, String friendlyId, String name, String createdByUserUuid,
                      ConferenceStatus status, Instant createdAt, Instant updatedAt,
                      Instant expiresAt, Double latitude, Double longitude,
                      String eventDate, String venue) {
        this.uuid = uuid;
        this.friendlyId = friendlyId;
        this.name = name;
        this.createdByUserUuid = createdByUserUuid;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.expiresAt = expiresAt;
        this.latitude = latitude;
        this.longitude = longitude;
        this.eventDate = eventDate;
        this.venue = venue;
    }

    public String getUuid() { return uuid; }
    public String getFriendlyId() { return friendlyId; }
    public String getName() { return name; }
    public String getCreatedByUserUuid() { return createdByUserUuid; }
    public ConferenceStatus getStatus() { return status; }
    public void setStatus(final ConferenceStatus status) { this.status = status; }
    public Instant getCreatedAt() { return createdAt; }
    public Instant getUpdatedAt() { return updatedAt; }
    public Instant getExpiresAt() { return expiresAt; }
    public Double getLatitude() { return latitude; }
    public Double getLongitude() { return longitude; }
    public String getEventDate() { return eventDate; }
    public String getVenue() { return venue; }
    public String getStartTime() { return startTime; }
    public String getEndTime() { return endTime; }
    public boolean isNameAutoGenerated() { return nameAutoGenerated; }
    public String getPresentationSourceUrl() { return presentationSourceUrl; }
    public String getOnDemandVideoProvider() { return onDemandVideoProvider; }
    public String getOnDemandVideoUrl() { return onDemandVideoUrl; }
    public String getFlyerBase64() { return flyerBase64; }
    public String getDescription() { return description; }
    public String getVisibility() { return visibility; }
    public String getScheduleMarkdown() { return scheduleMarkdown; }
    public String getScheduleLayout() { return scheduleLayout; }
    public String getPublicTheme() { return publicTheme; }
    public Integer getTimezoneId() { return timezoneId; }
    public Instant getReminderSentAt() { return reminderSentAt; }
    public Instant getDayBeforeReminderSentAt() { return dayBeforeReminderSentAt; }
    public String getSeatingMode() { return seatingMode; }
    public Integer getCapacity() { return capacity; }
    public int getReservedCount() { return reservedCount; }
    public String getTicketPrice() { return ticketPrice; }
    public String getTicketCurrency() { return ticketCurrency; }
    public boolean isTicketSalesEnabled() { return ticketSalesEnabled; }
    public boolean isFreeTicket() { return new BigDecimal(ticketPrice).signum() == 0; }
    public String getVenueMapBase64() { return venueMapBase64; }
    public String getEventTypeKey() { return eventTypeKey; }
    public Instant getNotesPurgedAt() { return notesPurgedAt; }
    public String getDiagramXml() { return diagramXml; }
    public String getDiagramPublishedSvg() { return diagramPublishedSvg; }
    public Instant getDiagramUpdatedAt() { return diagramUpdatedAt; }
    public long getDiagramVersion() { return diagramVersion; }
    public Instant getDiagramPurgedAt() { return diagramPurgedAt; }
    public String getWhiteboardSceneJson() { return whiteboardSceneJson; }
    public String getWhiteboardPublishedSvg() { return whiteboardPublishedSvg; }
    public Instant getWhiteboardUpdatedAt() { return whiteboardUpdatedAt; }
    public long getWhiteboardVersion() { return whiteboardVersion; }
    public void setDiagramXml(String diagramXml) {
        setDiagramXmlAndPublishedSvg(diagramXml, null);
    }
    public void setDiagramXmlAndPublishedSvg(String diagramXml, String publishedSvg) {
        this.diagramXml = diagramXml;
        this.diagramPublishedSvg = publishedSvg;
        this.diagramUpdatedAt = Instant.now();
        this.diagramVersion++;
    }
    /** Usado solo por el repositorio al reconstruir la entidad desde la BD (no actualiza updatedAt). */
    public void restoreDiagramXml(String diagramXml, Instant diagramUpdatedAt) {
        restoreDiagram(diagramXml, null, diagramUpdatedAt, 0);
    }
    /** Usado solo por el repositorio al reconstruir la entidad desde la BD. */
    public void restoreDiagram(String diagramXml, String publishedSvg, Instant diagramUpdatedAt, long version) {
        this.diagramXml = diagramXml;
        this.diagramPublishedSvg = publishedSvg;
        this.diagramUpdatedAt = diagramUpdatedAt;
        this.diagramVersion = version;
    }
    public void setDiagramPurgedAt(Instant diagramPurgedAt) { this.diagramPurgedAt = diagramPurgedAt; }
    public void setWhiteboardSceneAndPublishedSvg(String sceneJson, String publishedSvg) {
        this.whiteboardSceneJson = sceneJson;
        this.whiteboardPublishedSvg = publishedSvg;
        this.whiteboardUpdatedAt = Instant.now();
        this.whiteboardVersion++;
    }
    /** Usado solo por el repositorio al reconstruir la entidad desde la BD. */
    public void restoreWhiteboard(String sceneJson, String publishedSvg, Instant updatedAt, long version) {
        this.whiteboardSceneJson = sceneJson;
        this.whiteboardPublishedSvg = publishedSvg;
        this.whiteboardUpdatedAt = updatedAt;
        this.whiteboardVersion = version;
    }
    public void setSeatingMode(String seatingMode) { this.seatingMode = seatingMode; }
    public void setCapacity(Integer capacity) { this.capacity = capacity; }
    public void setReservedCount(int reservedCount) { this.reservedCount = reservedCount; }
    public void setTicketPrice(String ticketPrice) {
        if (ticketPrice == null || ticketPrice.isBlank()) {
            this.ticketPrice = "0.00";
            return;
        }
        try {
            final BigDecimal value = new BigDecimal(ticketPrice.trim());
            if (value.signum() < 0 || value.scale() > 2 || value.precision() > 12) {
                throw new IllegalArgumentException("ticket_price_invalid");
            }
            this.ticketPrice = value.setScale(2, RoundingMode.UNNECESSARY).toPlainString();
        } catch (NumberFormatException | ArithmeticException e) {
            throw new IllegalArgumentException("ticket_price_invalid", e);
        }
    }
    public void setTicketCurrency(String ticketCurrency) {
        final String normalized = ticketCurrency == null || ticketCurrency.isBlank()
                ? "MXN" : ticketCurrency.trim().toUpperCase(Locale.ROOT);
        if (!normalized.matches("[A-Z]{3}")) throw new IllegalArgumentException("ticket_currency_invalid");
        this.ticketCurrency = normalized;
    }
    public void setTicketSalesEnabled(boolean ticketSalesEnabled) { this.ticketSalesEnabled = ticketSalesEnabled; }
    public void setVenueMapBase64(String venueMapBase64) { this.venueMapBase64 = venueMapBase64; }
    public void setEventTypeKey(String eventTypeKey) { this.eventTypeKey = eventTypeKey; }
    public void setNotesPurgedAt(Instant notesPurgedAt) { this.notesPurgedAt = notesPurgedAt; }
    public void setEventDate(String eventDate) { this.eventDate = eventDate; }
    public void setVenue(String venue) { this.venue = venue; }
    public void setStartTime(String startTime) { this.startTime = startTime; }
    public void setEndTime(String endTime) { this.endTime = endTime; }
    public void setName(String name) { this.name = name; this.updatedAt = Instant.now(); }
    public void setLatitude(Double latitude) { this.latitude = latitude; }
    public void setLongitude(Double longitude) { this.longitude = longitude; }
    public void setNameAutoGenerated(boolean nameAutoGenerated) { this.nameAutoGenerated = nameAutoGenerated; }
    public void setPresentationSourceUrl(String presentationSourceUrl) { this.presentationSourceUrl = presentationSourceUrl; }
    public void setOnDemandVideoProvider(String onDemandVideoProvider) { this.onDemandVideoProvider = onDemandVideoProvider; }
    public void setOnDemandVideoUrl(String onDemandVideoUrl) { this.onDemandVideoUrl = onDemandVideoUrl; }
    public void setFlyerBase64(String flyerBase64) { this.flyerBase64 = flyerBase64; }
    public void setDescription(String description) { this.description = description; }
    public void setVisibility(String visibility) {
        this.visibility = "PUBLIC".equals(visibility) || "HYBRID".equals(visibility) ? visibility : "PRIVATE";
    }
    public void setScheduleMarkdown(String scheduleMarkdown) { this.scheduleMarkdown = scheduleMarkdown; }
    public void setScheduleLayout(String scheduleLayout) {
        this.scheduleLayout = "LEFT".equals(scheduleLayout) ? "LEFT" : "RIGHT";
    }
    public void setPublicTheme(String publicTheme) {
        this.publicTheme = switch (publicTheme == null ? "" : publicTheme.toUpperCase()) {
            case "EDITORIAL", "MINIMAL" -> publicTheme.toUpperCase();
            default -> "CLASSIC";
        };
    }
    public void setTimezoneId(Integer timezoneId) { this.timezoneId = timezoneId; }
    public void setReminderSentAt(Instant reminderSentAt) { this.reminderSentAt = reminderSentAt; }
    public void setDayBeforeReminderSentAt(Instant dayBeforeReminderSentAt) { this.dayBeforeReminderSentAt = dayBeforeReminderSentAt; }
    public String getSandboxVariant() { return sandboxVariant; }
    public Integer getSandboxPoolSize() { return sandboxPoolSize; }
    public Integer getSandboxInternetEnabled() { return sandboxInternetEnabled; }
    public String getSandboxRemoteGitUrl() { return sandboxRemoteGitUrl; }
    public Integer getSandboxJvmHeapMb() { return sandboxJvmHeapMb; }
    public Integer getSandboxSeatsPerPod() { return sandboxSeatsPerPod; }
    public Integer getSandboxCliPoolSize() { return sandboxCliPoolSize; }
    public Integer getSandboxCliLazyVimPoolSize() { return sandboxCliLazyVimPoolSize; }
    public void setSandboxVariant(String sandboxVariant) { this.sandboxVariant = sandboxVariant; }
    public void setSandboxPoolSize(Integer sandboxPoolSize) { this.sandboxPoolSize = sandboxPoolSize; }
    public void setSandboxCliPoolSize(Integer sandboxCliPoolSize) { this.sandboxCliPoolSize = sandboxCliPoolSize; }
    public void setSandboxCliLazyVimPoolSize(Integer sandboxCliLazyVimPoolSize) { this.sandboxCliLazyVimPoolSize = sandboxCliLazyVimPoolSize; }
    public void setSandboxInternetEnabled(Integer sandboxInternetEnabled) { this.sandboxInternetEnabled = sandboxInternetEnabled; }
    public void setSandboxRemoteGitUrl(String sandboxRemoteGitUrl) { this.sandboxRemoteGitUrl = sandboxRemoteGitUrl; }
    public void setSandboxJvmHeapMb(Integer sandboxJvmHeapMb) { this.sandboxJvmHeapMb = sandboxJvmHeapMb; }
    public void setSandboxSeatsPerPod(Integer sandboxSeatsPerPod) { this.sandboxSeatsPerPod = sandboxSeatsPerPod; }
    public Integer getMaxDevicesPerUser() { return maxDevicesPerUser; }
    public Integer getMaxAccountsPerDevice() { return maxAccountsPerDevice; }
    public CanvasTool getCanvasTool() { return canvasTool; }
    public CanvasAudienceMode getCanvasAudienceMode() { return canvasAudienceMode; }
    public List<CanvasConfig> getCanvasConfigs() { return canvasConfigs; }
    public List<OnDemandCuePoint> getOnDemandCuePoints() { return onDemandCuePoints; }
    public String getCertificateEngine() { return certificateEngine; }
    public void setCertificateEngine(final String certificateEngine) {
        this.certificateEngine = "HTML_CHROME".equals(certificateEngine) ? "HTML_CHROME" : "INHOUSE";
    }
    public void setMaxDevicesPerUser(Integer maxDevicesPerUser) { this.maxDevicesPerUser = maxDevicesPerUser; }
    public void setMaxAccountsPerDevice(Integer maxAccountsPerDevice) { this.maxAccountsPerDevice = maxAccountsPerDevice; }
    public void setCanvasTool(CanvasTool canvasTool) { this.canvasTool = canvasTool; }
    public void setCanvasAudienceMode(CanvasAudienceMode canvasAudienceMode) { this.canvasAudienceMode = canvasAudienceMode; }
    public void setCanvasConfigs(List<CanvasConfig> canvasConfigs) {
        this.canvasConfigs = canvasConfigs == null ? List.of() : List.copyOf(canvasConfigs);
    }
    public void setOnDemandCuePoints(List<OnDemandCuePoint> onDemandCuePoints) {
        this.onDemandCuePoints = onDemandCuePoints == null ? List.of() : List.copyOf(onDemandCuePoints);
    }
}
