package dev.rafex.insightbloom.users.domain.model;

import java.time.Instant;
import java.util.UUID;

public class Conference {
    private final String uuid;
    private final String friendlyId;
    private String name;
    private final String createdByUserUuid;
    private ConferenceStatus status;
    private final Instant createdAt;
    private Instant updatedAt;
    private Instant expiresAt; // nullable
    private Double latitude;
    private Double longitude;
    private String eventDate; // ISO-8601 date string, nullable
    private String venue; // nullable
    private String startTime; // HH:mm, nullable
    private String endTime; // HH:mm, nullable
    // true cuando el organizador no fijó un nombre de certificado explícito al crear/editar la
    // conferencia: permite que el título extraído del markdown de la presentación lo complete.
    private boolean nameAutoGenerated;
    private String presentationSourceUrl; // repo o descarga de la presentación, nullable
    private String flyerBase64; // imagen promocional opcional (data URL), nullable
    private Integer timezoneId; // FK a timezones, nullable (se resuelve al default si no se envía)
    private Instant reminderSentAt; // marca cuándo se envió el recordatorio de 1h antes, nullable
    private String seatingMode = "NONE"; // NONE | GENERAL | SEATED
    private Integer capacity; // aforo máximo, solo relevante en modo GENERAL
    private int reservedCount; // contador atómico de reservas activas en modo GENERAL
    private String venueMapBase64; // imagen del recinto (data URL) para modo SEATED, nullable
    private String eventTypeKey = "conference"; // FK a event_types.key; toda conferencia existente cae aquí
    private Instant notesPurgedAt; // marca cuándo se borró el pad de Etherpad (TTL, ver DEC-0020), nullable
    private String diagramXml; // ultimo XML guardado del diagrama de drawio, nullable
    private Instant diagramUpdatedAt; // nullable
    private Instant diagramPurgedAt; // marca cuándo se purgó el diagrama por TTL, nullable
    private String sandboxVariant; // python|java|web, solo si CODE_IDE habilitada, nullable
    private Integer sandboxPoolSize; // tamaño del pool de sandboxes, nullable
    private Integer sandboxInternetEnabled; // 0|1, por defecto 0
    private String sandboxExtraPackages; // paquetes adicionales a instalar, nullable
    private String sandboxRemoteGitUrl; // URL de remoto git del profesor, nullable
    // Heap maximo (-Xmx, en MB) de las JVMs dentro del sandbox (jdt.ls, java/mvn que corra el
    // alumno) -- nullable, si no se configura se usa un default chico pensado para cursos
    // (ver KubernetesPodClient). Clampeado contra el limite de memoria del contenedor
    // (SANDBOX_DEBIAN_MEMORY_LIMIT/SANDBOX_NEOVIM_MEMORY_LIMIT, ver SetSandboxConfigUseCase) --
    // nunca puede exceder ese techo, para que un heap mal configurado no tire el contenedor por OOM.
    private Integer sandboxJvmHeapMb;
    // Cantidad de alumnos que comparten UN mismo Pod "neovim" (varios usuarios Linux dentro del
    // mismo contenedor, cada uno con su propio home/ttyd) -- nullable, default efectivo 4 si no
    // se configura (ver AssignSandboxUseCase). Solo tiene efecto en modo terminal-nvim; en modo
    // debian se ignora (code-server no se puede compartir entre alumnos). Validado 1..10 en
    // SetSandboxConfigUseCase -- un numero mas alto exigiria revisar el LimitRange del namespace
    // a mano, no es un simple ajuste de config.
    private Integer sandboxSeatsPerPod;

    public Conference(String friendlyId, String name, String createdByUserUuid) {
        this.uuid = UUID.randomUUID().toString();
        this.friendlyId = friendlyId;
        this.name = name;
        this.createdByUserUuid = createdByUserUuid;
        this.status = ConferenceStatus.ACTIVE;
        this.createdAt = Instant.now();
        this.updatedAt = this.createdAt;
    }

    public Conference(String friendlyId, String name, String createdByUserUuid, Double latitude, Double longitude) {
        this(friendlyId, name, createdByUserUuid);
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public Conference(String friendlyId, String name, String createdByUserUuid, Instant expiresAt) {
        this(friendlyId, name, createdByUserUuid);
        this.expiresAt = expiresAt;
    }

    public Conference(String friendlyId, String name, String createdByUserUuid, Instant expiresAt, Double latitude, Double longitude) {
        this(friendlyId, name, createdByUserUuid);
        this.expiresAt = expiresAt;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public Conference(String uuid, String friendlyId, String name, String createdByUserUuid,
                      ConferenceStatus status, Instant createdAt, Instant updatedAt,
                      Instant expiresAt, Double latitude, Double longitude) {
        this(uuid, friendlyId, name, createdByUserUuid, status, createdAt, updatedAt,
                expiresAt, latitude, longitude, null, null);
    }

    public Conference(String uuid, String friendlyId, String name, String createdByUserUuid,
                      ConferenceStatus status, Instant createdAt, Instant updatedAt,
                      Instant expiresAt, Double latitude, Double longitude,
                      String eventDate, String venue) {
        this.uuid = uuid;
        this.friendlyId = friendlyId;
        this.name = name;
        this.createdByUserUuid = createdByUserUuid;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.expiresAt = expiresAt;
        this.latitude = latitude;
        this.longitude = longitude;
        this.eventDate = eventDate;
        this.venue = venue;
    }

    public String getUuid() { return uuid; }
    public String getFriendlyId() { return friendlyId; }
    public String getName() { return name; }
    public String getCreatedByUserUuid() { return createdByUserUuid; }
    public ConferenceStatus getStatus() { return status; }
    public Instant getCreatedAt() { return createdAt; }
    public Instant getUpdatedAt() { return updatedAt; }
    public Instant getExpiresAt() { return expiresAt; }
    public Double getLatitude() { return latitude; }
    public Double getLongitude() { return longitude; }
    public String getEventDate() { return eventDate; }
    public String getVenue() { return venue; }
    public String getStartTime() { return startTime; }
    public String getEndTime() { return endTime; }
    public boolean isNameAutoGenerated() { return nameAutoGenerated; }
    public String getPresentationSourceUrl() { return presentationSourceUrl; }
    public String getFlyerBase64() { return flyerBase64; }
    public Integer getTimezoneId() { return timezoneId; }
    public Instant getReminderSentAt() { return reminderSentAt; }
    public String getSeatingMode() { return seatingMode; }
    public Integer getCapacity() { return capacity; }
    public int getReservedCount() { return reservedCount; }
    public String getVenueMapBase64() { return venueMapBase64; }
    public String getEventTypeKey() { return eventTypeKey; }
    public Instant getNotesPurgedAt() { return notesPurgedAt; }
    public String getDiagramXml() { return diagramXml; }
    public Instant getDiagramUpdatedAt() { return diagramUpdatedAt; }
    public Instant getDiagramPurgedAt() { return diagramPurgedAt; }
    public void setDiagramXml(String diagramXml) { this.diagramXml = diagramXml; this.diagramUpdatedAt = Instant.now(); }
    /** Usado solo por el repositorio al reconstruir la entidad desde la BD (no actualiza updatedAt). */
    public void restoreDiagramXml(String diagramXml, Instant diagramUpdatedAt) {
        this.diagramXml = diagramXml;
        this.diagramUpdatedAt = diagramUpdatedAt;
    }
    public void setDiagramPurgedAt(Instant diagramPurgedAt) { this.diagramPurgedAt = diagramPurgedAt; }
    public void setSeatingMode(String seatingMode) { this.seatingMode = seatingMode; }
    public void setCapacity(Integer capacity) { this.capacity = capacity; }
    public void setReservedCount(int reservedCount) { this.reservedCount = reservedCount; }
    public void setVenueMapBase64(String venueMapBase64) { this.venueMapBase64 = venueMapBase64; }
    public void setEventTypeKey(String eventTypeKey) { this.eventTypeKey = eventTypeKey; }
    public void setNotesPurgedAt(Instant notesPurgedAt) { this.notesPurgedAt = notesPurgedAt; }
    public void setEventDate(String eventDate) { this.eventDate = eventDate; }
    public void setVenue(String venue) { this.venue = venue; }
    public void setStartTime(String startTime) { this.startTime = startTime; }
    public void setEndTime(String endTime) { this.endTime = endTime; }
    public void setName(String name) { this.name = name; this.updatedAt = Instant.now(); }
    public void setLatitude(Double latitude) { this.latitude = latitude; }
    public void setLongitude(Double longitude) { this.longitude = longitude; }
    public void setNameAutoGenerated(boolean nameAutoGenerated) { this.nameAutoGenerated = nameAutoGenerated; }
    public void setPresentationSourceUrl(String presentationSourceUrl) { this.presentationSourceUrl = presentationSourceUrl; }
    public void setFlyerBase64(String flyerBase64) { this.flyerBase64 = flyerBase64; }
    public void setTimezoneId(Integer timezoneId) { this.timezoneId = timezoneId; }
    public void setReminderSentAt(Instant reminderSentAt) { this.reminderSentAt = reminderSentAt; }
    public String getSandboxVariant() { return sandboxVariant; }
    public Integer getSandboxPoolSize() { return sandboxPoolSize; }
    public Integer getSandboxInternetEnabled() { return sandboxInternetEnabled; }
    public String getSandboxExtraPackages() { return sandboxExtraPackages; }
    public String getSandboxRemoteGitUrl() { return sandboxRemoteGitUrl; }
    public Integer getSandboxJvmHeapMb() { return sandboxJvmHeapMb; }
    public Integer getSandboxSeatsPerPod() { return sandboxSeatsPerPod; }
    public void setSandboxVariant(String sandboxVariant) { this.sandboxVariant = sandboxVariant; }
    public void setSandboxPoolSize(Integer sandboxPoolSize) { this.sandboxPoolSize = sandboxPoolSize; }
    public void setSandboxInternetEnabled(Integer sandboxInternetEnabled) { this.sandboxInternetEnabled = sandboxInternetEnabled; }
    public void setSandboxExtraPackages(String sandboxExtraPackages) { this.sandboxExtraPackages = sandboxExtraPackages; }
    public void setSandboxRemoteGitUrl(String sandboxRemoteGitUrl) { this.sandboxRemoteGitUrl = sandboxRemoteGitUrl; }
    public void setSandboxJvmHeapMb(Integer sandboxJvmHeapMb) { this.sandboxJvmHeapMb = sandboxJvmHeapMb; }
    public void setSandboxSeatsPerPod(Integer sandboxSeatsPerPod) { this.sandboxSeatsPerPod = sandboxSeatsPerPod; }
}
