{{- if and .Values.drawio.enabled .Values.autoscaling.enabled }}
{{- $minReplicas := .Values.drawio.autoscaling.minReplicas | default .Values.autoscaling.minReplicas }}
{{- $maxReplicas := .Values.drawio.autoscaling.maxReplicas | default .Values.autoscaling.maxReplicas }}
{{- $cpuTarget := .Values.drawio.autoscaling.targetCPUUtilizationPercentage | default .Values.autoscaling.targetCPUUtilizationPercentage }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "insightbloom.fullname" . }}-drawio
  labels:
    {{- include "insightbloom.labels" . | nindent 4 }}
    app.kubernetes.io/component: drawio
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "insightbloom.fullname" . }}-drawio
  minReplicas: {{ $minReplicas }}
  maxReplicas: {{ $maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $cpuTarget }}
{{- end }}
