{{- if .Values.drawio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "insightbloom.fullname" . }}-drawio
  labels:
    {{- include "insightbloom.labels" . | nindent 4 }}
    app.kubernetes.io/component: drawio
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.drawio.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "insightbloom.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: drawio
{{- end }}
