{{- if .Values.excalidraw.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "insightbloom.fullname" . }}-excalidraw
  labels:
    {{- include "insightbloom.labels" . | nindent 4 }}
    app.kubernetes.io/component: excalidraw
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.excalidraw.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "insightbloom.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: excalidraw
  template:
    metadata:
      labels:
        {{- include "insightbloom.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: excalidraw
    spec:
      serviceAccountName: {{ include "insightbloom.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: excalidraw
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.excalidraw.repository }}:{{ .Values.excalidraw.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.excalidraw.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.excalidraw.resources | nindent 12 }}
{{- end }}
