{{- range $name, $svc := .Values.services }}
{{- $enabled := dig "autoscaling" "enabled" $.Values.autoscaling.enabled $svc }}
{{- if $enabled }}
{{- $minReplicas := dig "autoscaling" "minReplicas" $.Values.autoscaling.minReplicas $svc }}
{{- $maxReplicas := dig "autoscaling" "maxReplicas" $.Values.autoscaling.maxReplicas $svc }}
{{- $cpuTarget  := dig "autoscaling" "targetCPUUtilizationPercentage" $.Values.autoscaling.targetCPUUtilizationPercentage $svc }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "insightbloom.fullname" $ }}-{{ $name }}
  labels:
    {{- include "insightbloom.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "insightbloom.fullname" $ }}-{{ $name }}
  minReplicas: {{ $minReplicas }}
  maxReplicas: {{ $maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $cpuTarget }}
---
{{- end }}
{{- end }}
