apiVersion: v1
kind: Service
metadata:
  name: {{ include "insightbloom.fullname" . }}-nats
  labels:
    {{- include "insightbloom.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.nats.port }}
      targetPort: client
      protocol: TCP
      name: client
  selector:
    {{- include "insightbloom.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nats
