package dev.rafex.insightbloom.users.application.usecases;

import dev.rafex.insightbloom.users.domain.model.Conference;
import dev.rafex.insightbloom.users.domain.model.CanvasConfig;
import dev.rafex.insightbloom.users.domain.model.EventRole;
import dev.rafex.insightbloom.users.domain.ports.ConferenceRepository;
import dev.rafex.insightbloom.users.domain.ports.EventRoleRepository;
import dev.rafex.insightbloom.users.domain.ports.TimezoneRepository;
import dev.rafex.insightbloom.users.domain.services.FriendlyIdService;

import java.time.Instant;
import java.util.List;

public class CreateConferenceUseCase {
    private static final String HOST_ROLE_KEY = "host";
    // El servidor tiene recursos finitos -- todo evento declara un aforo desde que se crea,
    // sin excepción para eventos virtuales (DEC 2026-07-18). 10 es el default conservador.
    private static final int DEFAULT_CAPACITY = 10;

    private final ConferenceRepository conferenceRepository;
    private final FriendlyIdService friendlyIdService;
    private final TimezoneRepository timezoneRepository;
    private final EventRoleRepository eventRoleRepository;
    private final TicketUseCase ticketUseCase;

    public CreateConferenceUseCase(ConferenceRepository conferenceRepository, FriendlyIdService friendlyIdService,
                                    TimezoneRepository timezoneRepository, EventRoleRepository eventRoleRepository) {
        this(conferenceRepository, friendlyIdService, timezoneRepository, eventRoleRepository, null);
    }

    public CreateConferenceUseCase(ConferenceRepository conferenceRepository, FriendlyIdService friendlyIdService,
                                    TimezoneRepository timezoneRepository, EventRoleRepository eventRoleRepository,
                                    TicketUseCase ticketUseCase) {
        this.conferenceRepository = conferenceRepository;
        this.friendlyIdService = friendlyIdService;
        this.timezoneRepository = timezoneRepository;
        this.eventRoleRepository = eventRoleRepository;
        this.ticketUseCase = ticketUseCase;
    }

    public record CreateRequest(String name, String displayName, String createdByUserUuid, String expiresAt,
                                Double latitude, Double longitude,
                                String eventDate, String venue, String startTime, String endTime,
                                Integer timezoneId, String eventTypeKey, Integer capacity,
                                String canvasTool, String canvasAudienceMode,
                                List<CanvasConfig> canvasConfigs, String certificateEngine,
                                String description, String visibility, String scheduleMarkdown,
                                String scheduleLayout) {}
    public record CreateResult(String conferenceId, String friendlyId, String name, String status,
                               String expiresAt, Double latitude, Double longitude,
                               String eventDate, String venue, String startTime, String endTime,
                               Integer timezoneId, String eventTypeKey, Integer capacity,
                               String canvasTool, String canvasAudienceMode,
                               List<CanvasConfig> canvasConfigs, String certificateEngine,
                               String description, String visibility, String scheduleMarkdown,
                               String scheduleLayout) {}

    public CreateResult execute(CreateRequest request) {
        final List<CanvasConfig> configs = request.canvasConfigs() != null
                ? List.copyOf(request.canvasConfigs())
                : legacyConfig(request.canvasTool(), request.canvasAudienceMode());
        validateCanvasConfigs(configs);
        String friendlyId = friendlyIdService.generate(request.name());
        boolean nameAutoGenerated = blankToNull(request.displayName()) == null;
        String displayName = nameAutoGenerated ? request.name() : request.displayName();
        Instant expiresAt = parseInstant(request.expiresAt());
        Conference conference = new Conference(friendlyId, displayName, request.createdByUserUuid(),
                expiresAt, request.latitude(), request.longitude());
        conference.setNameAutoGenerated(nameAutoGenerated);
        conference.setEventDate(blankToNull(request.eventDate()));
        conference.setVenue(blankToNull(request.venue()));
        conference.setStartTime(blankToNull(request.startTime()));
        conference.setEndTime(blankToNull(request.endTime()));
        conference.setDescription(boundedText(request.description(), 4000, "description_too_long"));
        conference.setVisibility(request.visibility());
        conference.setScheduleMarkdown(boundedText(request.scheduleMarkdown(), 12000, "schedule_too_long"));
        conference.setScheduleLayout(request.scheduleLayout());
        conference.setTimezoneId(request.timezoneId() != null ? request.timezoneId()
                : timezoneRepository.findDefault().id());
        if (blankToNull(request.eventTypeKey()) != null) {
            conference.setEventTypeKey(request.eventTypeKey());
        }
        conference.setCapacity(normalizeCapacity(request.capacity()));
        conference.setCertificateEngine(request.certificateEngine());
        conference.setCanvasConfigs(configs);
        conference.setCanvasTool(configs.size() == 1 ? configs.get(0).tool() : null);
        conference.setCanvasAudienceMode(configs.size() == 1 ? configs.get(0).audienceMode() : null);
        conferenceRepository.save(conference);
        conferenceRepository.replaceCanvasConfigs(conference.getUuid(), configs);
        // El creador se vuelve Host automaticamente (FR-004, DEC-0021) — sin accion manual.
        eventRoleRepository.save(new EventRole(conference.getUuid(), request.createdByUserUuid(), HOST_ROLE_KEY));
        if (ticketUseCase != null && ticketUseCase.isTicketed(conference)) {
            // El creador ocupa una plaza real desde el inicio. La segunda plaza queda disponible
            // para el primer asistente; por eso el backend nunca permite aforo menor a 2.
            ticketUseCase.issueOperational(conference.getUuid(), request.createdByUserUuid());
        }
        return new CreateResult(
            conference.getUuid(), conference.getFriendlyId(),
            conference.getName(), conference.getStatus().name().toLowerCase(),
            expiresAt != null ? expiresAt.toString() : null,
            conference.getLatitude(), conference.getLongitude(),
            conference.getEventDate(), conference.getVenue(),
            conference.getStartTime(), conference.getEndTime(),
            conference.getTimezoneId(), conference.getEventTypeKey(), conference.getCapacity(),
            conference.getCanvasTool(), conference.getCanvasAudienceMode(), conference.getCanvasConfigs(),
            conference.getCertificateEngine(), conference.getDescription(), conference.getVisibility(),
            conference.getScheduleMarkdown(), conference.getScheduleLayout()
        );
    }

    private static int normalizeCapacity(final Integer capacity) {
        if (capacity == null || capacity < 1) return Math.max(2, DEFAULT_CAPACITY);
        return Math.max(2, capacity);
    }

    private static String blankToNull(String s) {
        return (s == null || s.isBlank()) ? null : s;
    }

    private static String boundedText(String value, int maxLength, String errorCode) {
        String normalized = blankToNull(value);
        if (normalized != null && normalized.length() > maxLength) throw new IllegalArgumentException(errorCode);
        return normalized;
    }

    private static List<CanvasConfig> legacyConfig(final String canvasTool, final String audienceMode) {
        if (canvasTool == null || canvasTool.isBlank()) return List.of();
        return List.of(new CanvasConfig(canvasTool,
                audienceMode == null || audienceMode.isBlank()
                        ? (SetCanvasConfigUseCase.ETHERPAD.equals(canvasTool)
                            ? SetCanvasConfigUseCase.COLLABORATIVE : SetCanvasConfigUseCase.INDEPENDENT)
                        : audienceMode));
    }

    private static void validateCanvasConfigs(final List<CanvasConfig> configs) {
        final java.util.Set<String> tools = new java.util.HashSet<>();
        for (final CanvasConfig config : configs) {
            if (config == null || config.tool() == null || config.tool().isBlank()
                    || !tools.add(config.tool())) {
                throw new IllegalArgumentException("canvas_tool_invalid");
            }
            if (!SetCanvasConfigUseCase.DRAWIO.equals(config.tool())
                    && !SetCanvasConfigUseCase.EXCALIDRAW.equals(config.tool())
                    && !SetCanvasConfigUseCase.ETHERPAD.equals(config.tool())) {
                throw new IllegalArgumentException("canvas_tool_invalid");
            }
            final boolean supportedMode = SetCanvasConfigUseCase.ETHERPAD.equals(config.tool())
                    ? (SetCanvasConfigUseCase.INDEPENDENT.equals(config.audienceMode())
                        || SetCanvasConfigUseCase.COLLABORATIVE.equals(config.audienceMode()))
                    : (SetCanvasConfigUseCase.INDEPENDENT.equals(config.audienceMode())
                        || SetCanvasConfigUseCase.MODERATOR_ONLY.equals(config.audienceMode()));
            if (!supportedMode) {
                throw new IllegalArgumentException("canvas_audience_mode_invalid");
            }
        }
    }

    private static Instant parseInstant(String s) {
        if (s == null || s.isBlank()) return null;
        try { return Instant.parse(s); } catch (Exception e) { return null; }
    }
}
