package dev.rafex.insightbloom.users.application.usecases;

import dev.rafex.insightbloom.users.domain.model.Conference;
import dev.rafex.insightbloom.users.domain.ports.ConferenceRepository;

import java.util.Optional;

public class UpdateConferenceUseCase {
    private final ConferenceRepository conferenceRepository;

    public UpdateConferenceUseCase(final ConferenceRepository conferenceRepository) {
        this.conferenceRepository = conferenceRepository;
    }

    public record UpdateRequest(String displayName, String venue, String eventDate, String startTime,
                                 String endTime, Double latitude, Double longitude,
                                 String presentationSourceUrl, String flyerBase64, Integer timezoneId,
                                 String description, String visibility, String scheduleMarkdown,
                                 String scheduleLayout, String publicTheme,
                                 String ticketPrice, String ticketCurrency) {}

    /** Actualiza todo excepto friendlyId y uuid. Solo el creador puede editar. */
    public Optional<Conference> execute(final String uuid, final String requestingUserUuid,
                                         final UpdateRequest request) {
        validateCoordinates(request.latitude(), request.longitude());
        return conferenceRepository.findByUuid(uuid)
                .filter(c -> c.getCreatedByUserUuid().equals(requestingUserUuid))
                .map(c -> {
                    if (request.displayName() != null && !request.displayName().isBlank()) {
                        c.setName(request.displayName());
                        // Edición manual del organizador: ya no se debe sobrescribir con el
                        // título de una futura presentación subida.
                        c.setNameAutoGenerated(false);
                    }
                    c.setVenue(blankToNull(request.venue()));
                    final String newEventDate = blankToNull(request.eventDate());
                    final String newStartTime = blankToNull(request.startTime());
                    // Si cambió la fecha/hora del evento, el recordatorio ya enviado (si lo hubo)
                    // ya no aplica — se reprograma para la nueva hora.
                    if (!java.util.Objects.equals(c.getEventDate(), newEventDate)
                            || !java.util.Objects.equals(c.getStartTime(), newStartTime)) {
                        c.setReminderSentAt(null);
                    }
                    c.setEventDate(newEventDate);
                    c.setStartTime(newStartTime);
                    c.setEndTime(blankToNull(request.endTime()));
                    if (request.description() != null) {
                        c.setDescription(boundedText(request.description(), 4000, "description_too_long"));
                    }
                    if (request.visibility() != null) c.setVisibility(request.visibility());
                    if (request.scheduleMarkdown() != null) {
                        c.setScheduleMarkdown(boundedText(request.scheduleMarkdown(), 12000, "schedule_too_long"));
                    }
                    if (request.scheduleLayout() != null) c.setScheduleLayout(request.scheduleLayout());
                    if (request.publicTheme() != null) c.setPublicTheme(request.publicTheme());
                    if (request.ticketPrice() != null) c.setTicketPrice(request.ticketPrice());
                    if (request.ticketCurrency() != null) c.setTicketCurrency(request.ticketCurrency());
                    c.setLatitude(request.latitude());
                    c.setLongitude(request.longitude());
                    if (request.presentationSourceUrl() != null) {
                        c.setPresentationSourceUrl(blankToNull(request.presentationSourceUrl()));
                    }
                    if (request.flyerBase64() != null) {
                        c.setFlyerBase64(blankToNull(request.flyerBase64()));
                    }
                    if (request.timezoneId() != null) {
                        c.setTimezoneId(request.timezoneId());
                    }
                    conferenceRepository.save(c);
                    return c;
                });
    }

    /** Cambia únicamente la emisión pública de boletos; el evento y los boletos existentes siguen activos. */
    public Optional<Conference> setTicketSalesEnabled(final String uuid, final String requestingUserUuid,
                                                      final boolean enabled) {
        return conferenceRepository.findByUuid(uuid)
                .filter(c -> c.getCreatedByUserUuid().equals(requestingUserUuid))
                .map(c -> {
                    c.setTicketSalesEnabled(enabled);
                    conferenceRepository.save(c);
                    return c;
                });
    }

    /** Reemplaza el flyer después de validar y normalizar la imagen recibida por multipart. */
    public Optional<Conference> updateFlyer(final String uuid, final String requestingUserUuid,
                                            final byte[] imageBytes, final String contentType) {
        if (imageBytes == null || imageBytes.length == 0) {
            throw new IllegalArgumentException("flyer_empty");
        }
        if (!"image/png".equalsIgnoreCase(contentType) && !"image/jpeg".equalsIgnoreCase(contentType)) {
            throw new IllegalArgumentException("flyer_format_not_allowed");
        }
        final String dataUrl = "data:" + contentType.toLowerCase(java.util.Locale.ROOT)
                + ";base64," + java.util.Base64.getEncoder().encodeToString(imageBytes);
        final String normalized = EventFlyerNormalizer.normalize(dataUrl);
        return conferenceRepository.findByUuid(uuid)
                .filter(c -> c.getCreatedByUserUuid().equals(requestingUserUuid))
                .map(c -> {
                    c.setFlyerBase64(normalized);
                    conferenceRepository.save(c);
                    return c;
                });
    }

    /**
     * Completa el nombre de certificado con el título extraído del markdown de una presentación
     * recién subida, pero solo si el organizador nunca fijó un nombre explícito (create/edit).
     */
    public Optional<Conference> deriveNameFromPresentation(final String uuid, final String title) {
        if (title == null || title.isBlank()) return Optional.empty();
        return conferenceRepository.findByUuid(uuid)
                .filter(Conference::isNameAutoGenerated)
                .map(c -> {
                    c.setName(title.trim());
                    c.setNameAutoGenerated(true);
                    conferenceRepository.save(c);
                    return c;
                });
    }

    private static String blankToNull(final String s) {
        return (s == null || s.isBlank()) ? null : s;
    }

    private static void validateCoordinates(final Double latitude, final Double longitude) {
        if ((latitude == null) != (longitude == null)) {
            throw new IllegalArgumentException("coordinates_pair_required");
        }
        if (latitude != null && (!Double.isFinite(latitude) || latitude < -90 || latitude > 90
                || !Double.isFinite(longitude) || longitude < -180 || longitude > 180)) {
            throw new IllegalArgumentException("coordinates_out_of_range");
        }
    }

    private static String boundedText(final String value, final int maxLength, final String errorCode) {
        final String normalized = blankToNull(value);
        if (normalized != null && normalized.length() > maxLength) throw new IllegalArgumentException(errorCode);
        return normalized;
    }
}
