package dev.rafex.insightbloom.users.application.usecases;

import dev.rafex.insightbloom.users.domain.model.Conference;
import dev.rafex.insightbloom.users.domain.ports.ConferenceRepository;

import java.util.Optional;

public class UpdateConferenceUseCase {
    private final ConferenceRepository conferenceRepository;

    public UpdateConferenceUseCase(final ConferenceRepository conferenceRepository) {
        this.conferenceRepository = conferenceRepository;
    }

    public record UpdateRequest(String displayName, String venue, String eventDate, String startTime,
                                 String endTime, Double latitude, Double longitude,
                                 String presentationSourceUrl) {}

    /** Actualiza todo excepto friendlyId y uuid. Solo el creador puede editar. */
    public Optional<Conference> execute(final String uuid, final String requestingUserUuid,
                                         final UpdateRequest request) {
        return conferenceRepository.findByUuid(uuid)
                .filter(c -> c.getCreatedByUserUuid().equals(requestingUserUuid))
                .map(c -> {
                    if (request.displayName() != null && !request.displayName().isBlank()) {
                        c.setName(request.displayName());
                        // Edición manual del organizador: ya no se debe sobrescribir con el
                        // título de una futura presentación subida.
                        c.setNameAutoGenerated(false);
                    }
                    c.setVenue(blankToNull(request.venue()));
                    c.setEventDate(blankToNull(request.eventDate()));
                    c.setStartTime(blankToNull(request.startTime()));
                    c.setEndTime(blankToNull(request.endTime()));
                    c.setLatitude(request.latitude());
                    c.setLongitude(request.longitude());
                    if (request.presentationSourceUrl() != null) {
                        c.setPresentationSourceUrl(blankToNull(request.presentationSourceUrl()));
                    }
                    conferenceRepository.save(c);
                    return c;
                });
    }

    /**
     * Completa el nombre de certificado con el título extraído del markdown de una presentación
     * recién subida, pero solo si el organizador nunca fijó un nombre explícito (create/edit).
     */
    public Optional<Conference> deriveNameFromPresentation(final String uuid, final String title) {
        if (title == null || title.isBlank()) return Optional.empty();
        return conferenceRepository.findByUuid(uuid)
                .filter(Conference::isNameAutoGenerated)
                .map(c -> {
                    c.setName(title.trim());
                    c.setNameAutoGenerated(true);
                    conferenceRepository.save(c);
                    return c;
                });
    }

    private static String blankToNull(final String s) {
        return (s == null || s.isBlank()) ? null : s;
    }
}
