package dev.rafex.insightbloom.users.domain.services;

import com.fasterxml.jackson.databind.JsonNode;
import dev.rafex.ether.json.JacksonJsonCodec;

import java.util.List;
import java.util.Map;

/** Catálogo inmutable de diseños y variables permitidas para certificados. */
public final class CertificateTemplateCatalog {
    private CertificateTemplateCatalog() {}

    public record Entry(String key, String name, String description, String engine, String documentJson) {}
    public record Variable(String key, String label, String example) {}

    public static List<Entry> entries() {
        return List.of(
                new Entry("classic", "Clásico", "Diseño centrado con borde y datos esenciales.", "HTML_CHROME", classic()),
                new Entry("modern", "Moderno", "Banda de color y composición contemporánea.", "HTML_CHROME", modern()),
                new Entry("minimal", "Minimalista", "Diseño limpio para eventos cortos.", "HTML_CHROME", minimal())
        );
    }

    public static Entry defaultEntry() { return entries().get(0); }

    /**
     * Upgrades an untouched certificate generated by the first visual-editor
     * catalog. Those documents used only the upper 504 px of the 816 px
     * landscape page. Custom documents are deliberately left unchanged.
     */
    public static String upgradeLegacyLayout(final String templateKey, final String documentJson) {
        if (!List.of("classic", "modern", "minimal").contains(templateKey)
                || documentJson == null || documentJson.isBlank()) return documentJson;
        try {
            final JsonNode root = JacksonJsonCodec.defaultCodec().readTree(documentJson);
            final JsonNode page = root.path("page");
            final JsonNode blocks = root.path("blocks");
            if (!root.isObject() || !page.isObject() || page.has("layoutVersion")
                    || !blocks.isArray() || blocks.size() != 7) return documentJson;
            if (!isNumber(blocks.get(0), "x", 18) || !isNumber(blocks.get(0), "y", 18)
                    || !isNumber(blocks.get(0), "width", 964) || !isNumber(blocks.get(0), "height", 504)
                    || !"shape".equals(blocks.get(0).path("type").asText())) return documentJson;
            final String[] expectedText = {
                    "CERTIFICADO DE ASISTENCIA",
                    "Se otorga el presente certificado a",
                    "{{participant.displayName}}",
                    "por su participación en",
                    "{{event.name}}",
                    "Emitido el {{certificate.issuedDate}} · {{platform.name}}"
            };
            for (int i = 0; i < expectedText.length; i++) {
                if (!expectedText[i].equals(blocks.get(i + 1).path("text").asText())) return documentJson;
            }
            return entries().stream().filter(entry -> entry.key().equals(templateKey))
                    .map(Entry::documentJson).findFirst().orElse(documentJson);
        } catch (Exception ignored) {
            return documentJson;
        }
    }

    private static boolean isNumber(final JsonNode node, final String field, final int expected) {
        return node != null && node.path(field).isNumber() && node.path(field).asInt() == expected;
    }

    public static List<Variable> variables() {
        return List.of(
                new Variable("participant.displayName", "Nombre visible", "Ana Pérez"),
                new Variable("participant.firstName", "Nombre", "Ana"),
                new Variable("participant.lastName", "Apellidos", "Pérez"),
                new Variable("participant.email", "Correo", "ana@example.com"),
                new Variable("participant.username", "Usuario", "ana.perez"),
                new Variable("participant.uuid", "ID del participante", "uuid"),
                new Variable("event.name", "Nombre del evento", "Taller de ejemplo"),
                new Variable("event.displayName", "Nombre mostrado del evento", "Taller de ejemplo"),
                new Variable("event.friendlyId", "ID amigable", "taller-ejemplo"),
                new Variable("event.uuid", "ID del evento", "uuid"),
                new Variable("event.date", "Fecha del evento", "22/07/2026"),
                new Variable("event.startTime", "Hora de inicio", "09:00"),
                new Variable("event.endTime", "Hora de cierre", "13:00"),
                new Variable("event.venue", "Lugar", "Auditorio principal"),
                new Variable("event.timezone", "Zona horaria", "America/Mexico_City"),
                new Variable("platform.name", "Nombre de la plataforma", "InsightBloom"),
                new Variable("platform.website", "Sitio de la plataforma", "https://insightbloom.v1.rafex.cloud"),
                new Variable("platform.email", "Correo de contacto", "rafex@rafex.dev"),
                new Variable("platform.github", "GitHub", "https://github.com/rafex"),
                new Variable("platform.linkedin", "LinkedIn", "https://linkedin.com/in/soft-architect-raul-gonzalez"),
                new Variable("platform.telegram", "Telegram", "https://t.me/tabernadelanoche"),
                new Variable("certificate.issuedDate", "Fecha de emisión", "22/07/2026"),
                new Variable("certificate.id", "ID del certificado", "cert-uuid")
        );
    }

    /**
     * Letter landscape at 96 DPI: 11in x 8.5in = 1056 x 816 CSS pixels.
     * Keep the catalog layout in the same coordinate system as the HTML renderer
     * and the visual editor so the preview and the generated PDF have identical
     * proportions.
     */
    private static String document(final String background, final String accent, final String titleSize) {
        return """
                {"page":{"background":"%s","padding":18,"width":1056,"height":816,"orientation":"landscape","layoutVersion":2},"blocks":[
                {"type":"shape","x":18,"y":18,"width":1020,"height":780,"style":{"border":"3px solid %s","borderRadius":18}},
                {"type":"text","x":72,"y":94,"width":912,"height":58,"text":"CERTIFICADO DE ASISTENCIA","style":{"fontSize":%s,"fontWeight":700,"color":"%s","textAlign":"center"}},
                {"type":"text","x":72,"y":236,"width":912,"height":38,"text":"Se otorga el presente certificado a","style":{"fontSize":20,"color":"#4b5563","textAlign":"center"}},
                {"type":"text","x":72,"y":300,"width":912,"height":72,"text":"{{participant.displayName}}","style":{"fontSize":42,"fontWeight":700,"color":"%s","textAlign":"center"}},
                {"type":"text","x":72,"y":430,"width":912,"height":38,"text":"por su participación en","style":{"fontSize":20,"color":"#4b5563","textAlign":"center"}},
                {"type":"text","x":72,"y":488,"width":912,"height":58,"text":"{{event.name}}","style":{"fontSize":28,"fontWeight":600,"color":"%s","textAlign":"center"}},
                {"type":"text","x":72,"y":680,"width":912,"height":28,"text":"Emitido el {{certificate.issuedDate}} · {{platform.name}}","style":{"fontSize":14,"color":"#6b7280","textAlign":"center"}}
                ]}
                """.formatted(background, accent, titleSize, accent, accent, accent).replace("\n", "");
    }

    private static String classic() { return document("#ffffff", "#1e1b4b", "34"); }
    private static String modern() { return document("#f8fafc", "#4f46e5", "36"); }
    private static String minimal() { return document("#ffffff", "#111827", "32"); }
}
